#import modules
import openpyxl
import random
import re

#Player Name/Hero dictionary and set variable for below function
y=0
Player_List = {}


#Function to populate dictionary with player name/Hero
def Player_Creation(Hero):
    global y
    for row in sheet_obj.iter_rows(1):
        for cell in row:
            if cell.value == Hero:
                z = (sheet_obj.cell(row=(cell.row), column=(2)).value)
                x = 0
                if z == 0:
                    pass
                else:
                    while x < int(z):
                        New_Player = "Player" + str(y)
                        Player_List[New_Player] = Hero
                        y +=1
                        x +=1
                return y

 

#Set Excel defaults for player input
path = "Input Data.xlsx"
wb_obj = openpyxl.load_workbook(path, data_only=True)
wb_obj.active = wb_obj['Data Input']
sheet_obj = wb_obj.active

#Populate Dictionary with Player names/Heroes
Player_Creation("Arakni")
Player_Creation("Azalea")
Player_Creation("Betsy")
Player_Creation("Bravo")
Player_Creation("DIO")
Player_Creation("Dash") 
Player_Creation("Dorinthea")
Player_Creation("Enigma")
Player_Creation("Fai")
Player_Creation("Kano") 
Player_Creation("Kassai")
Player_Creation("Katsu")
Player_Creation("Kayo")
Player_Creation("Levia")
Player_Creation("Maxx")
Player_Creation("Nuu")
Player_Creation("Olympia")
Player_Creation("Prism")
Player_Creation("Rhinar") 
Player_Creation("Riptide")
Player_Creation("Boltyn")
Player_Creation("Teklovossen")
Player_Creation("Uzuri")
Player_Creation("Victor") 
Player_Creation("Viserai")
Player_Creation("Vynnset")
Player_Creation("Zen")

#Set player total and rounds
Month = ((sheet_obj.cell(row=(30),column=(2))).value)
Players = ((sheet_obj.cell(row=(31),column=(2))).value)
Sheet_Name = ((sheet_obj.cell(row=(36),column=(2))).value)
Day2_Cut = ((sheet_obj.cell(row=(33),column=(2))).value)
if Day2_Cut == str(True):
    Day1 = ((sheet_obj.cell(row=(34),column=(2))).value)
    Day2 = ((sheet_obj.cell(row=(35),column=(2))).value)
else:
    Rounds = sheet_obj.cell(row=(32),column=(2)).value

#List for just player names/Heroes
players = Player_List.fromkeys(Player_List)


#Set defaults for Excel to Matchup Data
path = "Talishar Meta Data.xlsx"
wb_obj = openpyxl.load_workbook(path, data_only=True)
wb_obj.active = wb_obj[Month]
sheet_obj = wb_obj.active

#dictionaries for winrates
Matchups = {
    'Arakni':{'First':{"Arakni":(sheet_obj.cell(row = (2), column = 3).value),"Azalea":(sheet_obj.cell(row = (2), column = 4).value),"Betsy":(sheet_obj.cell(row = (2), column = 5).value),"Bravo":(sheet_obj.cell(row = (2), column = 6).value),"DIO":(sheet_obj.cell(row = (2), column = 7).value),"Dash":(sheet_obj.cell(row = (2), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (2), column = 9).value),"Fai":(sheet_obj.cell(row = (2), column = 10).value),"Kano":(sheet_obj.cell(row = (2), column = 11).value),"Kassai":(sheet_obj.cell(row = (2), column = 12).value),"Katsu":(sheet_obj.cell(row = (2), column = 13).value),"Kayo":(sheet_obj.cell(row = (2), column = 14).value),"Levia":(sheet_obj.cell(row = (2), column = 15).value),"Maxx":(sheet_obj.cell(row = (2), column = 16).value),"Olympia":(sheet_obj.cell(row = (2), column = 17).value),"Prism":(sheet_obj.cell(row = (2), column = 18).value),"Rhinar":(sheet_obj.cell(row = (2), column = 19).value),"Riptide":(sheet_obj.cell(row = (2), column = 20).value),"Boltyn":(sheet_obj.cell(row = (2), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (2), column = 22).value),"Uzuri":(sheet_obj.cell(row = (2), column = 23).value),"Victor":(sheet_obj.cell(row = (2), column = 24).value),"Viserai":(sheet_obj.cell(row = (2), column = 25).value),"Vynnset":(sheet_obj.cell(row = (2), column = 26).value),"Enigma":(sheet_obj.cell(row = (2), column = 27).value),"Nuu":(sheet_obj.cell(row = (2), column = 28).value),"Zen":(sheet_obj.cell(row = (2), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (3), column = 3).value),"Azalea":(sheet_obj.cell(row = (3), column = 4).value),"Betsy":(sheet_obj.cell(row = (3), column = 5).value),"Bravo":(sheet_obj.cell(row = (3), column = 6).value),"DIO":(sheet_obj.cell(row = (3), column = 7).value),"Dash":(sheet_obj.cell(row = (3), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (3), column = 9).value),"Fai":(sheet_obj.cell(row = (3), column = 10).value),"Kano":(sheet_obj.cell(row = (3), column = 11).value),"Kassai":(sheet_obj.cell(row = (3), column = 12).value),"Katsu":(sheet_obj.cell(row = (3), column = 13).value),"Kayo":(sheet_obj.cell(row = (3), column = 14).value),"Levia":(sheet_obj.cell(row = (3), column = 15).value),"Maxx":(sheet_obj.cell(row = (3), column = 16).value),"Olympia":(sheet_obj.cell(row = (3), column = 17).value),"Prism":(sheet_obj.cell(row = (3), column = 18).value),"Rhinar":(sheet_obj.cell(row = (3), column = 19).value),"Riptide":(sheet_obj.cell(row = (3), column = 20).value),"Boltyn":(sheet_obj.cell(row = (3), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (3), column = 22).value),"Uzuri":(sheet_obj.cell(row = (3), column = 23).value),"Victor":(sheet_obj.cell(row = (3), column = 24).value),"Viserai":(sheet_obj.cell(row = (3), column = 25).value),"Vynnset":(sheet_obj.cell(row = (3), column = 26).value),"Enigma":(sheet_obj.cell(row = (3), column = 27).value),"Nuu":(sheet_obj.cell(row = (3), column = 28).value),"Zen":(sheet_obj.cell(row = (3), column = 29).value)}},
    'Azalea':{'First':{"Arakni":(sheet_obj.cell(row = (4), column = 3).value),"Azalea":(sheet_obj.cell(row = (4), column = 4).value),"Betsy":(sheet_obj.cell(row = (4), column = 5).value),"Bravo":(sheet_obj.cell(row = (4), column = 6).value),"DIO":(sheet_obj.cell(row = (4), column = 7).value),"Dash":(sheet_obj.cell(row = (4), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (4), column = 9).value),"Fai":(sheet_obj.cell(row = (4), column = 10).value),"Kano":(sheet_obj.cell(row = (4), column = 11).value),"Kassai":(sheet_obj.cell(row = (4), column = 12).value),"Katsu":(sheet_obj.cell(row = (4), column = 13).value),"Kayo":(sheet_obj.cell(row = (4), column = 14).value),"Levia":(sheet_obj.cell(row = (4), column = 15).value),"Maxx":(sheet_obj.cell(row = (4), column = 16).value),"Olympia":(sheet_obj.cell(row = (4), column = 17).value),"Prism":(sheet_obj.cell(row = (4), column = 18).value),"Rhinar":(sheet_obj.cell(row = (4), column = 19).value),"Riptide":(sheet_obj.cell(row = (4), column = 20).value),"Boltyn":(sheet_obj.cell(row = (4), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (4), column = 22).value),"Uzuri":(sheet_obj.cell(row = (4), column = 23).value),"Victor":(sheet_obj.cell(row = (4), column = 24).value),"Viserai":(sheet_obj.cell(row = (4), column = 25).value),"Vynnset":(sheet_obj.cell(row = (4), column = 26).value),"Enigma":(sheet_obj.cell(row = (4), column = 27).value),"Nuu":(sheet_obj.cell(row = (4), column = 28).value),"Zen":(sheet_obj.cell(row = (4), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (5), column = 3).value),"Azalea":(sheet_obj.cell(row = (5), column = 4).value),"Betsy":(sheet_obj.cell(row = (5), column = 5).value),"Bravo":(sheet_obj.cell(row = (5), column = 6).value),"DIO":(sheet_obj.cell(row = (5), column = 7).value),"Dash":(sheet_obj.cell(row = (5), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (5), column = 9).value),"Fai":(sheet_obj.cell(row = (5), column = 10).value),"Kano":(sheet_obj.cell(row = (5), column = 11).value),"Kassai":(sheet_obj.cell(row = (5), column = 12).value),"Katsu":(sheet_obj.cell(row = (5), column = 13).value),"Kayo":(sheet_obj.cell(row = (5), column = 14).value),"Levia":(sheet_obj.cell(row = (5), column = 15).value),"Maxx":(sheet_obj.cell(row = (5), column = 16).value),"Olympia":(sheet_obj.cell(row = (5), column = 17).value),"Prism":(sheet_obj.cell(row = (5), column = 18).value),"Rhinar":(sheet_obj.cell(row = (5), column = 19).value),"Riptide":(sheet_obj.cell(row = (5), column = 20).value),"Boltyn":(sheet_obj.cell(row = (5), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (5), column = 22).value),"Uzuri":(sheet_obj.cell(row = (5), column = 23).value),"Victor":(sheet_obj.cell(row = (5), column = 24).value),"Viserai":(sheet_obj.cell(row = (5), column = 25).value),"Vynnset":(sheet_obj.cell(row = (5), column = 26).value),"Enigma":(sheet_obj.cell(row = (5), column = 27).value),"Nuu":(sheet_obj.cell(row = (5), column = 28).value),"Zen":(sheet_obj.cell(row = (5), column = 29).value)}},
    'Betsy':{'First':{"Arakni":(sheet_obj.cell(row = (6), column = 3).value),"Azalea":(sheet_obj.cell(row = (6), column = 4).value),"Betsy":(sheet_obj.cell(row = (6), column = 5).value),"Bravo":(sheet_obj.cell(row = (6), column = 6).value),"DIO":(sheet_obj.cell(row = (6), column = 7).value),"Dash":(sheet_obj.cell(row = (6), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (6), column = 9).value),"Fai":(sheet_obj.cell(row = (6), column = 10).value),"Kano":(sheet_obj.cell(row = (6), column = 11).value),"Kassai":(sheet_obj.cell(row = (6), column = 12).value),"Katsu":(sheet_obj.cell(row = (6), column = 13).value),"Kayo":(sheet_obj.cell(row = (6), column = 14).value),"Levia":(sheet_obj.cell(row = (6), column = 15).value),"Maxx":(sheet_obj.cell(row = (6), column = 16).value),"Olympia":(sheet_obj.cell(row = (6), column = 17).value),"Prism":(sheet_obj.cell(row = (6), column = 18).value),"Rhinar":(sheet_obj.cell(row = (6), column = 19).value),"Riptide":(sheet_obj.cell(row = (6), column = 20).value),"Boltyn":(sheet_obj.cell(row = (6), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (6), column = 22).value),"Uzuri":(sheet_obj.cell(row = (6), column = 23).value),"Victor":(sheet_obj.cell(row = (6), column = 24).value),"Viserai":(sheet_obj.cell(row = (6), column = 25).value),"Vynnset":(sheet_obj.cell(row = (6), column = 26).value),"Enigma":(sheet_obj.cell(row = (6), column = 27).value),"Nuu":(sheet_obj.cell(row = (6), column = 28).value),"Zen":(sheet_obj.cell(row = (6), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (7), column = 3).value),"Azalea":(sheet_obj.cell(row = (7), column = 4).value),"Betsy":(sheet_obj.cell(row = (7), column = 5).value),"Bravo":(sheet_obj.cell(row = (7), column = 6).value),"DIO":(sheet_obj.cell(row = (7), column = 7).value),"Dash":(sheet_obj.cell(row = (7), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (7), column = 9).value),"Fai":(sheet_obj.cell(row = (7), column = 10).value),"Kano":(sheet_obj.cell(row = (7), column = 11).value),"Kassai":(sheet_obj.cell(row = (7), column = 12).value),"Katsu":(sheet_obj.cell(row = (7), column = 13).value),"Kayo":(sheet_obj.cell(row = (7), column = 14).value),"Levia":(sheet_obj.cell(row = (7), column = 15).value),"Maxx":(sheet_obj.cell(row = (7), column = 16).value),"Olympia":(sheet_obj.cell(row = (7), column = 17).value),"Prism":(sheet_obj.cell(row = (7), column = 18).value),"Rhinar":(sheet_obj.cell(row = (7), column = 19).value),"Riptide":(sheet_obj.cell(row = (7), column = 20).value),"Boltyn":(sheet_obj.cell(row = (7), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (7), column = 22).value),"Uzuri":(sheet_obj.cell(row = (7), column = 23).value),"Victor":(sheet_obj.cell(row = (7), column = 24).value),"Viserai":(sheet_obj.cell(row = (7), column = 25).value),"Vynnset":(sheet_obj.cell(row = (7), column = 26).value),"Enigma":(sheet_obj.cell(row = (7), column = 27).value),"Nuu":(sheet_obj.cell(row = (7), column = 28).value),"Zen":(sheet_obj.cell(row = (7), column = 29).value)}},
    'Bravo':{'First':{"Arakni":(sheet_obj.cell(row = (8), column = 3).value),"Azalea":(sheet_obj.cell(row = (8), column = 4).value),"Betsy":(sheet_obj.cell(row = (8), column = 5).value),"Bravo":(sheet_obj.cell(row = (8), column = 6).value),"DIO":(sheet_obj.cell(row = (8), column = 7).value),"Dash":(sheet_obj.cell(row = (8), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (8), column = 9).value),"Fai":(sheet_obj.cell(row = (8), column = 10).value),"Kano":(sheet_obj.cell(row = (8), column = 11).value),"Kassai":(sheet_obj.cell(row = (8), column = 12).value),"Katsu":(sheet_obj.cell(row = (8), column = 13).value),"Kayo":(sheet_obj.cell(row = (8), column = 14).value),"Levia":(sheet_obj.cell(row = (8), column = 15).value),"Maxx":(sheet_obj.cell(row = (8), column = 16).value),"Olympia":(sheet_obj.cell(row = (8), column = 17).value),"Prism":(sheet_obj.cell(row = (8), column = 18).value),"Rhinar":(sheet_obj.cell(row = (8), column = 19).value),"Riptide":(sheet_obj.cell(row = (8), column = 20).value),"Boltyn":(sheet_obj.cell(row = (8), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (8), column = 22).value),"Uzuri":(sheet_obj.cell(row = (8), column = 23).value),"Victor":(sheet_obj.cell(row = (8), column = 24).value),"Viserai":(sheet_obj.cell(row = (8), column = 25).value),"Vynnset":(sheet_obj.cell(row = (8), column = 26).value),"Enigma":(sheet_obj.cell(row = (8), column = 27).value),"Nuu":(sheet_obj.cell(row = (8), column = 28).value),"Zen":(sheet_obj.cell(row = (8), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (9), column = 3).value),"Azalea":(sheet_obj.cell(row = (9), column = 4).value),"Betsy":(sheet_obj.cell(row = (9), column = 5).value),"Bravo":(sheet_obj.cell(row = (9), column = 6).value),"DIO":(sheet_obj.cell(row = (9), column = 7).value),"Dash":(sheet_obj.cell(row = (9), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (9), column = 9).value),"Fai":(sheet_obj.cell(row = (9), column = 10).value),"Kano":(sheet_obj.cell(row = (9), column = 11).value),"Kassai":(sheet_obj.cell(row = (9), column = 12).value),"Katsu":(sheet_obj.cell(row = (9), column = 13).value),"Kayo":(sheet_obj.cell(row = (9), column = 14).value),"Levia":(sheet_obj.cell(row = (9), column = 15).value),"Maxx":(sheet_obj.cell(row = (9), column = 16).value),"Olympia":(sheet_obj.cell(row = (9), column = 17).value),"Prism":(sheet_obj.cell(row = (9), column = 18).value),"Rhinar":(sheet_obj.cell(row = (9), column = 19).value),"Riptide":(sheet_obj.cell(row = (9), column = 20).value),"Boltyn":(sheet_obj.cell(row = (9), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (9), column = 22).value),"Uzuri":(sheet_obj.cell(row = (9), column = 23).value),"Victor":(sheet_obj.cell(row = (9), column = 24).value),"Viserai":(sheet_obj.cell(row = (9), column = 25).value),"Vynnset":(sheet_obj.cell(row = (9), column = 26).value),"Enigma":(sheet_obj.cell(row = (9), column = 27).value),"Nuu":(sheet_obj.cell(row = (9), column = 28).value),"Zen":(sheet_obj.cell(row = (9), column = 29).value)}},
    'DIO':{'First':{"Arakni":(sheet_obj.cell(row = (10), column = 3).value),"Azalea":(sheet_obj.cell(row = (10), column = 4).value),"Betsy":(sheet_obj.cell(row = (10), column = 5).value),"Bravo":(sheet_obj.cell(row = (10), column = 6).value),"DIO":(sheet_obj.cell(row = (10), column = 7).value),"Dash":(sheet_obj.cell(row = (10), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (10), column = 9).value),"Fai":(sheet_obj.cell(row = (10), column = 10).value),"Kano":(sheet_obj.cell(row = (10), column = 11).value),"Kassai":(sheet_obj.cell(row = (10), column = 12).value),"Katsu":(sheet_obj.cell(row = (10), column = 13).value),"Kayo":(sheet_obj.cell(row = (10), column = 14).value),"Levia":(sheet_obj.cell(row = (10), column = 15).value),"Maxx":(sheet_obj.cell(row = (10), column = 16).value),"Olympia":(sheet_obj.cell(row = (10), column = 17).value),"Prism":(sheet_obj.cell(row = (10), column = 18).value),"Rhinar":(sheet_obj.cell(row = (10), column = 19).value),"Riptide":(sheet_obj.cell(row = (10), column = 20).value),"Boltyn":(sheet_obj.cell(row = (10), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (10), column = 22).value),"Uzuri":(sheet_obj.cell(row = (10), column = 23).value),"Victor":(sheet_obj.cell(row = (10), column = 24).value),"Viserai":(sheet_obj.cell(row = (10), column = 25).value),"Vynnset":(sheet_obj.cell(row = (10), column = 26).value),"Enigma":(sheet_obj.cell(row = (10), column = 27).value),"Nuu":(sheet_obj.cell(row = (10), column = 28).value),"Zen":(sheet_obj.cell(row = (10), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (11), column = 3).value),"Azalea":(sheet_obj.cell(row = (11), column = 4).value),"Betsy":(sheet_obj.cell(row = (11), column = 5).value),"Bravo":(sheet_obj.cell(row = (11), column = 6).value),"DIO":(sheet_obj.cell(row = (11), column = 7).value),"Dash":(sheet_obj.cell(row = (11), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (11), column = 9).value),"Fai":(sheet_obj.cell(row = (11), column = 10).value),"Kano":(sheet_obj.cell(row = (11), column = 11).value),"Kassai":(sheet_obj.cell(row = (11), column = 12).value),"Katsu":(sheet_obj.cell(row = (11), column = 13).value),"Kayo":(sheet_obj.cell(row = (11), column = 14).value),"Levia":(sheet_obj.cell(row = (11), column = 15).value),"Maxx":(sheet_obj.cell(row = (11), column = 16).value),"Olympia":(sheet_obj.cell(row = (11), column = 17).value),"Prism":(sheet_obj.cell(row = (11), column = 18).value),"Rhinar":(sheet_obj.cell(row = (11), column = 19).value),"Riptide":(sheet_obj.cell(row = (11), column = 20).value),"Boltyn":(sheet_obj.cell(row = (11), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (11), column = 22).value),"Uzuri":(sheet_obj.cell(row = (11), column = 23).value),"Victor":(sheet_obj.cell(row = (11), column = 24).value),"Viserai":(sheet_obj.cell(row = (11), column = 25).value),"Vynnset":(sheet_obj.cell(row = (11), column = 26).value),"Enigma":(sheet_obj.cell(row = (11), column = 27).value),"Nuu":(sheet_obj.cell(row = (11), column = 28).value),"Zen":(sheet_obj.cell(row = (11), column = 29).value)}},
    'Dash':{'First':{"Arakni":(sheet_obj.cell(row = (12), column = 3).value),"Azalea":(sheet_obj.cell(row = (12), column = 4).value),"Betsy":(sheet_obj.cell(row = (12), column = 5).value),"Bravo":(sheet_obj.cell(row = (12), column = 6).value),"DIO":(sheet_obj.cell(row = (12), column = 7).value),"Dash":(sheet_obj.cell(row = (12), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (12), column = 9).value),"Fai":(sheet_obj.cell(row = (12), column = 10).value),"Kano":(sheet_obj.cell(row = (12), column = 11).value),"Kassai":(sheet_obj.cell(row = (12), column = 12).value),"Katsu":(sheet_obj.cell(row = (12), column = 13).value),"Kayo":(sheet_obj.cell(row = (12), column = 14).value),"Levia":(sheet_obj.cell(row = (12), column = 15).value),"Maxx":(sheet_obj.cell(row = (12), column = 16).value),"Olympia":(sheet_obj.cell(row = (12), column = 17).value),"Prism":(sheet_obj.cell(row = (12), column = 18).value),"Rhinar":(sheet_obj.cell(row = (12), column = 19).value),"Riptide":(sheet_obj.cell(row = (12), column = 20).value),"Boltyn":(sheet_obj.cell(row = (12), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (12), column = 22).value),"Uzuri":(sheet_obj.cell(row = (12), column = 23).value),"Victor":(sheet_obj.cell(row = (12), column = 24).value),"Viserai":(sheet_obj.cell(row = (12), column = 25).value),"Vynnset":(sheet_obj.cell(row = (12), column = 26).value),"Enigma":(sheet_obj.cell(row = (12), column = 27).value),"Nuu":(sheet_obj.cell(row = (12), column = 28).value),"Zen":(sheet_obj.cell(row = (12), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (13), column = 3).value),"Azalea":(sheet_obj.cell(row = (13), column = 4).value),"Betsy":(sheet_obj.cell(row = (13), column = 5).value),"Bravo":(sheet_obj.cell(row = (13), column = 6).value),"DIO":(sheet_obj.cell(row = (13), column = 7).value),"Dash":(sheet_obj.cell(row = (13), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (13), column = 9).value),"Fai":(sheet_obj.cell(row = (13), column = 10).value),"Kano":(sheet_obj.cell(row = (13), column = 11).value),"Kassai":(sheet_obj.cell(row = (13), column = 12).value),"Katsu":(sheet_obj.cell(row = (13), column = 13).value),"Kayo":(sheet_obj.cell(row = (13), column = 14).value),"Levia":(sheet_obj.cell(row = (13), column = 15).value),"Maxx":(sheet_obj.cell(row = (13), column = 16).value),"Olympia":(sheet_obj.cell(row = (13), column = 17).value),"Prism":(sheet_obj.cell(row = (13), column = 18).value),"Rhinar":(sheet_obj.cell(row = (13), column = 19).value),"Riptide":(sheet_obj.cell(row = (13), column = 20).value),"Boltyn":(sheet_obj.cell(row = (13), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (13), column = 22).value),"Uzuri":(sheet_obj.cell(row = (13), column = 23).value),"Victor":(sheet_obj.cell(row = (13), column = 24).value),"Viserai":(sheet_obj.cell(row = (13), column = 25).value),"Vynnset":(sheet_obj.cell(row = (13), column = 26).value),"Enigma":(sheet_obj.cell(row = (13), column = 27).value),"Nuu":(sheet_obj.cell(row = (13), column = 28).value),"Zen":(sheet_obj.cell(row = (13), column = 29).value)}},
    'Dorinthea':{'First':{"Arakni":(sheet_obj.cell(row = (14), column = 3).value),"Azalea":(sheet_obj.cell(row = (14), column = 4).value),"Betsy":(sheet_obj.cell(row = (14), column = 5).value),"Bravo":(sheet_obj.cell(row = (14), column = 6).value),"DIO":(sheet_obj.cell(row = (14), column = 7).value),"Dash":(sheet_obj.cell(row = (14), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (14), column = 9).value),"Fai":(sheet_obj.cell(row = (14), column = 10).value),"Kano":(sheet_obj.cell(row = (14), column = 11).value),"Kassai":(sheet_obj.cell(row = (14), column = 12).value),"Katsu":(sheet_obj.cell(row = (14), column = 13).value),"Kayo":(sheet_obj.cell(row = (14), column = 14).value),"Levia":(sheet_obj.cell(row = (14), column = 15).value),"Maxx":(sheet_obj.cell(row = (14), column = 16).value),"Olympia":(sheet_obj.cell(row = (14), column = 17).value),"Prism":(sheet_obj.cell(row = (14), column = 18).value),"Rhinar":(sheet_obj.cell(row = (14), column = 19).value),"Riptide":(sheet_obj.cell(row = (14), column = 20).value),"Boltyn":(sheet_obj.cell(row = (14), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (14), column = 22).value),"Uzuri":(sheet_obj.cell(row = (14), column = 23).value),"Victor":(sheet_obj.cell(row = (14), column = 24).value),"Viserai":(sheet_obj.cell(row = (14), column = 25).value),"Vynnset":(sheet_obj.cell(row = (14), column = 26).value),"Enigma":(sheet_obj.cell(row = (14), column = 27).value),"Nuu":(sheet_obj.cell(row = (14), column = 28).value),"Zen":(sheet_obj.cell(row = (14), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (15), column = 3).value),"Azalea":(sheet_obj.cell(row = (15), column = 4).value),"Betsy":(sheet_obj.cell(row = (15), column = 5).value),"Bravo":(sheet_obj.cell(row = (15), column = 6).value),"DIO":(sheet_obj.cell(row = (15), column = 7).value),"Dash":(sheet_obj.cell(row = (15), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (15), column = 9).value),"Fai":(sheet_obj.cell(row = (15), column = 10).value),"Kano":(sheet_obj.cell(row = (15), column = 11).value),"Kassai":(sheet_obj.cell(row = (15), column = 12).value),"Katsu":(sheet_obj.cell(row = (15), column = 13).value),"Kayo":(sheet_obj.cell(row = (15), column = 14).value),"Levia":(sheet_obj.cell(row = (15), column = 15).value),"Maxx":(sheet_obj.cell(row = (15), column = 16).value),"Olympia":(sheet_obj.cell(row = (15), column = 17).value),"Prism":(sheet_obj.cell(row = (15), column = 18).value),"Rhinar":(sheet_obj.cell(row = (15), column = 19).value),"Riptide":(sheet_obj.cell(row = (15), column = 20).value),"Boltyn":(sheet_obj.cell(row = (15), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (15), column = 22).value),"Uzuri":(sheet_obj.cell(row = (15), column = 23).value),"Victor":(sheet_obj.cell(row = (15), column = 24).value),"Viserai":(sheet_obj.cell(row = (15), column = 25).value),"Vynnset":(sheet_obj.cell(row = (15), column = 26).value),"Enigma":(sheet_obj.cell(row = (15), column = 27).value),"Nuu":(sheet_obj.cell(row = (15), column = 28).value),"Zen":(sheet_obj.cell(row = (15), column = 29).value)}},
    'Fai':{'First':{"Arakni":(sheet_obj.cell(row = (16), column = 3).value),"Azalea":(sheet_obj.cell(row = (16), column = 4).value),"Betsy":(sheet_obj.cell(row = (16), column = 5).value),"Bravo":(sheet_obj.cell(row = (16), column = 6).value),"DIO":(sheet_obj.cell(row = (16), column = 7).value),"Dash":(sheet_obj.cell(row = (16), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (16), column = 9).value),"Fai":(sheet_obj.cell(row = (16), column = 10).value),"Kano":(sheet_obj.cell(row = (16), column = 11).value),"Kassai":(sheet_obj.cell(row = (16), column = 12).value),"Katsu":(sheet_obj.cell(row = (16), column = 13).value),"Kayo":(sheet_obj.cell(row = (16), column = 14).value),"Levia":(sheet_obj.cell(row = (16), column = 15).value),"Maxx":(sheet_obj.cell(row = (16), column = 16).value),"Olympia":(sheet_obj.cell(row = (16), column = 17).value),"Prism":(sheet_obj.cell(row = (16), column = 18).value),"Rhinar":(sheet_obj.cell(row = (16), column = 19).value),"Riptide":(sheet_obj.cell(row = (16), column = 20).value),"Boltyn":(sheet_obj.cell(row = (16), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (16), column = 22).value),"Uzuri":(sheet_obj.cell(row = (16), column = 23).value),"Victor":(sheet_obj.cell(row = (16), column = 24).value),"Viserai":(sheet_obj.cell(row = (16), column = 25).value),"Vynnset":(sheet_obj.cell(row = (16), column = 26).value),"Enigma":(sheet_obj.cell(row = (16), column = 27).value),"Nuu":(sheet_obj.cell(row = (16), column = 28).value),"Zen":(sheet_obj.cell(row = (16), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (17), column = 3).value),"Azalea":(sheet_obj.cell(row = (17), column = 4).value),"Betsy":(sheet_obj.cell(row = (17), column = 5).value),"Bravo":(sheet_obj.cell(row = (17), column = 6).value),"DIO":(sheet_obj.cell(row = (17), column = 7).value),"Dash":(sheet_obj.cell(row = (17), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (17), column = 9).value),"Fai":(sheet_obj.cell(row = (17), column = 10).value),"Kano":(sheet_obj.cell(row = (17), column = 11).value),"Kassai":(sheet_obj.cell(row = (17), column = 12).value),"Katsu":(sheet_obj.cell(row = (17), column = 13).value),"Kayo":(sheet_obj.cell(row = (17), column = 14).value),"Levia":(sheet_obj.cell(row = (17), column = 15).value),"Maxx":(sheet_obj.cell(row = (17), column = 16).value),"Olympia":(sheet_obj.cell(row = (17), column = 17).value),"Prism":(sheet_obj.cell(row = (17), column = 18).value),"Rhinar":(sheet_obj.cell(row = (17), column = 19).value),"Riptide":(sheet_obj.cell(row = (17), column = 20).value),"Boltyn":(sheet_obj.cell(row = (17), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (17), column = 22).value),"Uzuri":(sheet_obj.cell(row = (17), column = 23).value),"Victor":(sheet_obj.cell(row = (17), column = 24).value),"Viserai":(sheet_obj.cell(row = (17), column = 25).value),"Vynnset":(sheet_obj.cell(row = (17), column = 26).value),"Enigma":(sheet_obj.cell(row = (17), column = 27).value),"Nuu":(sheet_obj.cell(row = (17), column = 28).value),"Zen":(sheet_obj.cell(row = (17), column = 29).value)}},
    'Kano':{'First':{"Arakni":(sheet_obj.cell(row = (18), column = 3).value),"Azalea":(sheet_obj.cell(row = (18), column = 4).value),"Betsy":(sheet_obj.cell(row = (18), column = 5).value),"Bravo":(sheet_obj.cell(row = (18), column = 6).value),"DIO":(sheet_obj.cell(row = (18), column = 7).value),"Dash":(sheet_obj.cell(row = (18), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (18), column = 9).value),"Fai":(sheet_obj.cell(row = (18), column = 10).value),"Kano":(sheet_obj.cell(row = (18), column = 11).value),"Kassai":(sheet_obj.cell(row = (18), column = 12).value),"Katsu":(sheet_obj.cell(row = (18), column = 13).value),"Kayo":(sheet_obj.cell(row = (18), column = 14).value),"Levia":(sheet_obj.cell(row = (18), column = 15).value),"Maxx":(sheet_obj.cell(row = (18), column = 16).value),"Olympia":(sheet_obj.cell(row = (18), column = 17).value),"Prism":(sheet_obj.cell(row = (18), column = 18).value),"Rhinar":(sheet_obj.cell(row = (18), column = 19).value),"Riptide":(sheet_obj.cell(row = (18), column = 20).value),"Boltyn":(sheet_obj.cell(row = (18), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (18), column = 22).value),"Uzuri":(sheet_obj.cell(row = (18), column = 23).value),"Victor":(sheet_obj.cell(row = (18), column = 24).value),"Viserai":(sheet_obj.cell(row = (18), column = 25).value),"Vynnset":(sheet_obj.cell(row = (18), column = 26).value),"Enigma":(sheet_obj.cell(row = (18), column = 27).value),"Nuu":(sheet_obj.cell(row = (18), column = 28).value),"Zen":(sheet_obj.cell(row = (18), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (19), column = 3).value),"Azalea":(sheet_obj.cell(row = (19), column = 4).value),"Betsy":(sheet_obj.cell(row = (19), column = 5).value),"Bravo":(sheet_obj.cell(row = (19), column = 6).value),"DIO":(sheet_obj.cell(row = (19), column = 7).value),"Dash":(sheet_obj.cell(row = (19), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (19), column = 9).value),"Fai":(sheet_obj.cell(row = (19), column = 10).value),"Kano":(sheet_obj.cell(row = (19), column = 11).value),"Kassai":(sheet_obj.cell(row = (19), column = 12).value),"Katsu":(sheet_obj.cell(row = (19), column = 13).value),"Kayo":(sheet_obj.cell(row = (19), column = 14).value),"Levia":(sheet_obj.cell(row = (19), column = 15).value),"Maxx":(sheet_obj.cell(row = (19), column = 16).value),"Olympia":(sheet_obj.cell(row = (19), column = 17).value),"Prism":(sheet_obj.cell(row = (19), column = 18).value),"Rhinar":(sheet_obj.cell(row = (19), column = 19).value),"Riptide":(sheet_obj.cell(row = (19), column = 20).value),"Boltyn":(sheet_obj.cell(row = (19), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (19), column = 22).value),"Uzuri":(sheet_obj.cell(row = (19), column = 23).value),"Victor":(sheet_obj.cell(row = (19), column = 24).value),"Viserai":(sheet_obj.cell(row = (19), column = 25).value),"Vynnset":(sheet_obj.cell(row = (19), column = 26).value),"Enigma":(sheet_obj.cell(row = (19), column = 27).value),"Nuu":(sheet_obj.cell(row = (19), column = 28).value),"Zen":(sheet_obj.cell(row = (19), column = 29).value)}},
    'Kassai':{'First':{"Arakni":(sheet_obj.cell(row = (20), column = 3).value),"Azalea":(sheet_obj.cell(row = (20), column = 4).value),"Betsy":(sheet_obj.cell(row = (20), column = 5).value),"Bravo":(sheet_obj.cell(row = (20), column = 6).value),"DIO":(sheet_obj.cell(row = (20), column = 7).value),"Dash":(sheet_obj.cell(row = (20), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (20), column = 9).value),"Fai":(sheet_obj.cell(row = (20), column = 10).value),"Kano":(sheet_obj.cell(row = (20), column = 11).value),"Kassai":(sheet_obj.cell(row = (20), column = 12).value),"Katsu":(sheet_obj.cell(row = (20), column = 13).value),"Kayo":(sheet_obj.cell(row = (20), column = 14).value),"Levia":(sheet_obj.cell(row = (20), column = 15).value),"Maxx":(sheet_obj.cell(row = (20), column = 16).value),"Olympia":(sheet_obj.cell(row = (20), column = 17).value),"Prism":(sheet_obj.cell(row = (20), column = 18).value),"Rhinar":(sheet_obj.cell(row = (20), column = 19).value),"Riptide":(sheet_obj.cell(row = (20), column = 20).value),"Boltyn":(sheet_obj.cell(row = (20), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (20), column = 22).value),"Uzuri":(sheet_obj.cell(row = (20), column = 23).value),"Victor":(sheet_obj.cell(row = (20), column = 24).value),"Viserai":(sheet_obj.cell(row = (20), column = 25).value),"Vynnset":(sheet_obj.cell(row = (20), column = 26).value),"Enigma":(sheet_obj.cell(row = (20), column = 27).value),"Nuu":(sheet_obj.cell(row = (20), column = 28).value),"Zen":(sheet_obj.cell(row = (20), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (21), column = 3).value),"Azalea":(sheet_obj.cell(row = (21), column = 4).value),"Betsy":(sheet_obj.cell(row = (21), column = 5).value),"Bravo":(sheet_obj.cell(row = (21), column = 6).value),"DIO":(sheet_obj.cell(row = (21), column = 7).value),"Dash":(sheet_obj.cell(row = (21), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (21), column = 9).value),"Fai":(sheet_obj.cell(row = (21), column = 10).value),"Kano":(sheet_obj.cell(row = (21), column = 11).value),"Kassai":(sheet_obj.cell(row = (21), column = 12).value),"Katsu":(sheet_obj.cell(row = (21), column = 13).value),"Kayo":(sheet_obj.cell(row = (21), column = 14).value),"Levia":(sheet_obj.cell(row = (21), column = 15).value),"Maxx":(sheet_obj.cell(row = (21), column = 16).value),"Olympia":(sheet_obj.cell(row = (21), column = 17).value),"Prism":(sheet_obj.cell(row = (21), column = 18).value),"Rhinar":(sheet_obj.cell(row = (21), column = 19).value),"Riptide":(sheet_obj.cell(row = (21), column = 20).value),"Boltyn":(sheet_obj.cell(row = (21), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (21), column = 22).value),"Uzuri":(sheet_obj.cell(row = (21), column = 23).value),"Victor":(sheet_obj.cell(row = (21), column = 24).value),"Viserai":(sheet_obj.cell(row = (21), column = 25).value),"Vynnset":(sheet_obj.cell(row = (21), column = 26).value),"Enigma":(sheet_obj.cell(row = (21), column = 27).value),"Nuu":(sheet_obj.cell(row = (21), column = 28).value),"Zen":(sheet_obj.cell(row = (21), column = 29).value)}},
    'Katsu':{'First':{"Arakni":(sheet_obj.cell(row = (22), column = 3).value),"Azalea":(sheet_obj.cell(row = (22), column = 4).value),"Betsy":(sheet_obj.cell(row = (22), column = 5).value),"Bravo":(sheet_obj.cell(row = (22), column = 6).value),"DIO":(sheet_obj.cell(row = (22), column = 7).value),"Dash":(sheet_obj.cell(row = (22), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (22), column = 9).value),"Fai":(sheet_obj.cell(row = (22), column = 10).value),"Kano":(sheet_obj.cell(row = (22), column = 11).value),"Kassai":(sheet_obj.cell(row = (22), column = 12).value),"Katsu":(sheet_obj.cell(row = (22), column = 13).value),"Kayo":(sheet_obj.cell(row = (22), column = 14).value),"Levia":(sheet_obj.cell(row = (22), column = 15).value),"Maxx":(sheet_obj.cell(row = (22), column = 16).value),"Olympia":(sheet_obj.cell(row = (22), column = 17).value),"Prism":(sheet_obj.cell(row = (22), column = 18).value),"Rhinar":(sheet_obj.cell(row = (22), column = 19).value),"Riptide":(sheet_obj.cell(row = (22), column = 20).value),"Boltyn":(sheet_obj.cell(row = (22), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (22), column = 22).value),"Uzuri":(sheet_obj.cell(row = (22), column = 23).value),"Victor":(sheet_obj.cell(row = (22), column = 24).value),"Viserai":(sheet_obj.cell(row = (22), column = 25).value),"Vynnset":(sheet_obj.cell(row = (22), column = 26).value),"Enigma":(sheet_obj.cell(row = (22), column = 27).value),"Nuu":(sheet_obj.cell(row = (22), column = 28).value),"Zen":(sheet_obj.cell(row = (22), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (23), column = 3).value),"Azalea":(sheet_obj.cell(row = (23), column = 4).value),"Betsy":(sheet_obj.cell(row = (23), column = 5).value),"Bravo":(sheet_obj.cell(row = (23), column = 6).value),"DIO":(sheet_obj.cell(row = (23), column = 7).value),"Dash":(sheet_obj.cell(row = (23), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (23), column = 9).value),"Fai":(sheet_obj.cell(row = (23), column = 10).value),"Kano":(sheet_obj.cell(row = (23), column = 11).value),"Kassai":(sheet_obj.cell(row = (23), column = 12).value),"Katsu":(sheet_obj.cell(row = (23), column = 13).value),"Kayo":(sheet_obj.cell(row = (23), column = 14).value),"Levia":(sheet_obj.cell(row = (23), column = 15).value),"Maxx":(sheet_obj.cell(row = (23), column = 16).value),"Olympia":(sheet_obj.cell(row = (23), column = 17).value),"Prism":(sheet_obj.cell(row = (23), column = 18).value),"Rhinar":(sheet_obj.cell(row = (23), column = 19).value),"Riptide":(sheet_obj.cell(row = (23), column = 20).value),"Boltyn":(sheet_obj.cell(row = (23), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (23), column = 22).value),"Uzuri":(sheet_obj.cell(row = (23), column = 23).value),"Victor":(sheet_obj.cell(row = (23), column = 24).value),"Viserai":(sheet_obj.cell(row = (23), column = 25).value),"Vynnset":(sheet_obj.cell(row = (23), column = 26).value),"Enigma":(sheet_obj.cell(row = (23), column = 27).value),"Nuu":(sheet_obj.cell(row = (23), column = 28).value),"Zen":(sheet_obj.cell(row = (23), column = 29).value)}},
    'Kayo':{'First':{"Arakni":(sheet_obj.cell(row = (24), column = 3).value),"Azalea":(sheet_obj.cell(row = (24), column = 4).value),"Betsy":(sheet_obj.cell(row = (24), column = 5).value),"Bravo":(sheet_obj.cell(row = (24), column = 6).value),"DIO":(sheet_obj.cell(row = (24), column = 7).value),"Dash":(sheet_obj.cell(row = (24), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (24), column = 9).value),"Fai":(sheet_obj.cell(row = (24), column = 10).value),"Kano":(sheet_obj.cell(row = (24), column = 11).value),"Kassai":(sheet_obj.cell(row = (24), column = 12).value),"Katsu":(sheet_obj.cell(row = (24), column = 13).value),"Kayo":(sheet_obj.cell(row = (24), column = 14).value),"Levia":(sheet_obj.cell(row = (24), column = 15).value),"Maxx":(sheet_obj.cell(row = (24), column = 16).value),"Olympia":(sheet_obj.cell(row = (24), column = 17).value),"Prism":(sheet_obj.cell(row = (24), column = 18).value),"Rhinar":(sheet_obj.cell(row = (24), column = 19).value),"Riptide":(sheet_obj.cell(row = (24), column = 20).value),"Boltyn":(sheet_obj.cell(row = (24), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (24), column = 22).value),"Uzuri":(sheet_obj.cell(row = (24), column = 23).value),"Victor":(sheet_obj.cell(row = (24), column = 24).value),"Viserai":(sheet_obj.cell(row = (24), column = 25).value),"Vynnset":(sheet_obj.cell(row = (24), column = 26).value),"Enigma":(sheet_obj.cell(row = (24), column = 27).value),"Nuu":(sheet_obj.cell(row = (24), column = 28).value),"Zen":(sheet_obj.cell(row = (24), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (25), column = 3).value),"Azalea":(sheet_obj.cell(row = (25), column = 4).value),"Betsy":(sheet_obj.cell(row = (25), column = 5).value),"Bravo":(sheet_obj.cell(row = (25), column = 6).value),"DIO":(sheet_obj.cell(row = (25), column = 7).value),"Dash":(sheet_obj.cell(row = (25), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (25), column = 9).value),"Fai":(sheet_obj.cell(row = (25), column = 10).value),"Kano":(sheet_obj.cell(row = (25), column = 11).value),"Kassai":(sheet_obj.cell(row = (25), column = 12).value),"Katsu":(sheet_obj.cell(row = (25), column = 13).value),"Kayo":(sheet_obj.cell(row = (25), column = 14).value),"Levia":(sheet_obj.cell(row = (25), column = 15).value),"Maxx":(sheet_obj.cell(row = (25), column = 16).value),"Olympia":(sheet_obj.cell(row = (25), column = 17).value),"Prism":(sheet_obj.cell(row = (25), column = 18).value),"Rhinar":(sheet_obj.cell(row = (25), column = 19).value),"Riptide":(sheet_obj.cell(row = (25), column = 20).value),"Boltyn":(sheet_obj.cell(row = (25), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (25), column = 22).value),"Uzuri":(sheet_obj.cell(row = (25), column = 23).value),"Victor":(sheet_obj.cell(row = (25), column = 24).value),"Viserai":(sheet_obj.cell(row = (25), column = 25).value),"Vynnset":(sheet_obj.cell(row = (25), column = 26).value),"Enigma":(sheet_obj.cell(row = (25), column = 27).value),"Nuu":(sheet_obj.cell(row = (25), column = 28).value),"Zen":(sheet_obj.cell(row = (25), column = 29).value)}},
    'Levia':{'First':{"Arakni":(sheet_obj.cell(row = (26), column = 3).value),"Azalea":(sheet_obj.cell(row = (26), column = 4).value),"Betsy":(sheet_obj.cell(row = (26), column = 5).value),"Bravo":(sheet_obj.cell(row = (26), column = 6).value),"DIO":(sheet_obj.cell(row = (26), column = 7).value),"Dash":(sheet_obj.cell(row = (26), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (26), column = 9).value),"Fai":(sheet_obj.cell(row = (26), column = 10).value),"Kano":(sheet_obj.cell(row = (26), column = 11).value),"Kassai":(sheet_obj.cell(row = (26), column = 12).value),"Katsu":(sheet_obj.cell(row = (26), column = 13).value),"Kayo":(sheet_obj.cell(row = (26), column = 14).value),"Levia":(sheet_obj.cell(row = (26), column = 15).value),"Maxx":(sheet_obj.cell(row = (26), column = 16).value),"Olympia":(sheet_obj.cell(row = (26), column = 17).value),"Prism":(sheet_obj.cell(row = (26), column = 18).value),"Rhinar":(sheet_obj.cell(row = (26), column = 19).value),"Riptide":(sheet_obj.cell(row = (26), column = 20).value),"Boltyn":(sheet_obj.cell(row = (26), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (26), column = 22).value),"Uzuri":(sheet_obj.cell(row = (26), column = 23).value),"Victor":(sheet_obj.cell(row = (26), column = 24).value),"Viserai":(sheet_obj.cell(row = (26), column = 25).value),"Vynnset":(sheet_obj.cell(row = (26), column = 26).value),"Enigma":(sheet_obj.cell(row = (26), column = 27).value),"Nuu":(sheet_obj.cell(row = (26), column = 28).value),"Zen":(sheet_obj.cell(row = (26), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (27), column = 3).value),"Azalea":(sheet_obj.cell(row = (27), column = 4).value),"Betsy":(sheet_obj.cell(row = (27), column = 5).value),"Bravo":(sheet_obj.cell(row = (27), column = 6).value),"DIO":(sheet_obj.cell(row = (27), column = 7).value),"Dash":(sheet_obj.cell(row = (27), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (27), column = 9).value),"Fai":(sheet_obj.cell(row = (27), column = 10).value),"Kano":(sheet_obj.cell(row = (27), column = 11).value),"Kassai":(sheet_obj.cell(row = (27), column = 12).value),"Katsu":(sheet_obj.cell(row = (27), column = 13).value),"Kayo":(sheet_obj.cell(row = (27), column = 14).value),"Levia":(sheet_obj.cell(row = (27), column = 15).value),"Maxx":(sheet_obj.cell(row = (27), column = 16).value),"Olympia":(sheet_obj.cell(row = (27), column = 17).value),"Prism":(sheet_obj.cell(row = (27), column = 18).value),"Rhinar":(sheet_obj.cell(row = (27), column = 19).value),"Riptide":(sheet_obj.cell(row = (27), column = 20).value),"Boltyn":(sheet_obj.cell(row = (27), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (27), column = 22).value),"Uzuri":(sheet_obj.cell(row = (27), column = 23).value),"Victor":(sheet_obj.cell(row = (27), column = 24).value),"Viserai":(sheet_obj.cell(row = (27), column = 25).value),"Vynnset":(sheet_obj.cell(row = (27), column = 26).value),"Enigma":(sheet_obj.cell(row = (27), column = 27).value),"Nuu":(sheet_obj.cell(row = (27), column = 28).value),"Zen":(sheet_obj.cell(row = (27), column = 29).value)}},
    'Maxx':{'First':{"Arakni":(sheet_obj.cell(row = (28), column = 3).value),"Azalea":(sheet_obj.cell(row = (28), column = 4).value),"Betsy":(sheet_obj.cell(row = (28), column = 5).value),"Bravo":(sheet_obj.cell(row = (28), column = 6).value),"DIO":(sheet_obj.cell(row = (28), column = 7).value),"Dash":(sheet_obj.cell(row = (28), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (28), column = 9).value),"Fai":(sheet_obj.cell(row = (28), column = 10).value),"Kano":(sheet_obj.cell(row = (28), column = 11).value),"Kassai":(sheet_obj.cell(row = (28), column = 12).value),"Katsu":(sheet_obj.cell(row = (28), column = 13).value),"Kayo":(sheet_obj.cell(row = (28), column = 14).value),"Levia":(sheet_obj.cell(row = (28), column = 15).value),"Maxx":(sheet_obj.cell(row = (28), column = 16).value),"Olympia":(sheet_obj.cell(row = (28), column = 17).value),"Prism":(sheet_obj.cell(row = (28), column = 18).value),"Rhinar":(sheet_obj.cell(row = (28), column = 19).value),"Riptide":(sheet_obj.cell(row = (28), column = 20).value),"Boltyn":(sheet_obj.cell(row = (28), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (28), column = 22).value),"Uzuri":(sheet_obj.cell(row = (28), column = 23).value),"Victor":(sheet_obj.cell(row = (28), column = 24).value),"Viserai":(sheet_obj.cell(row = (28), column = 25).value),"Vynnset":(sheet_obj.cell(row = (28), column = 26).value),"Enigma":(sheet_obj.cell(row = (28), column = 27).value),"Nuu":(sheet_obj.cell(row = (28), column = 28).value),"Zen":(sheet_obj.cell(row = (28), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (29), column = 3).value),"Azalea":(sheet_obj.cell(row = (29), column = 4).value),"Betsy":(sheet_obj.cell(row = (29), column = 5).value),"Bravo":(sheet_obj.cell(row = (29), column = 6).value),"DIO":(sheet_obj.cell(row = (29), column = 7).value),"Dash":(sheet_obj.cell(row = (29), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (29), column = 9).value),"Fai":(sheet_obj.cell(row = (29), column = 10).value),"Kano":(sheet_obj.cell(row = (29), column = 11).value),"Kassai":(sheet_obj.cell(row = (29), column = 12).value),"Katsu":(sheet_obj.cell(row = (29), column = 13).value),"Kayo":(sheet_obj.cell(row = (29), column = 14).value),"Levia":(sheet_obj.cell(row = (29), column = 15).value),"Maxx":(sheet_obj.cell(row = (29), column = 16).value),"Olympia":(sheet_obj.cell(row = (29), column = 17).value),"Prism":(sheet_obj.cell(row = (29), column = 18).value),"Rhinar":(sheet_obj.cell(row = (29), column = 19).value),"Riptide":(sheet_obj.cell(row = (29), column = 20).value),"Boltyn":(sheet_obj.cell(row = (29), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (29), column = 22).value),"Uzuri":(sheet_obj.cell(row = (29), column = 23).value),"Victor":(sheet_obj.cell(row = (29), column = 24).value),"Viserai":(sheet_obj.cell(row = (29), column = 25).value),"Vynnset":(sheet_obj.cell(row = (29), column = 26).value),"Enigma":(sheet_obj.cell(row = (29), column = 27).value),"Nuu":(sheet_obj.cell(row = (29), column = 28).value),"Zen":(sheet_obj.cell(row = (29), column = 29).value)}},
    'Olympia':{'First':{"Arakni":(sheet_obj.cell(row = (30), column = 3).value),"Azalea":(sheet_obj.cell(row = (30), column = 4).value),"Betsy":(sheet_obj.cell(row = (30), column = 5).value),"Bravo":(sheet_obj.cell(row = (30), column = 6).value),"DIO":(sheet_obj.cell(row = (30), column = 7).value),"Dash":(sheet_obj.cell(row = (30), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (30), column = 9).value),"Fai":(sheet_obj.cell(row = (30), column = 10).value),"Kano":(sheet_obj.cell(row = (30), column = 11).value),"Kassai":(sheet_obj.cell(row = (30), column = 12).value),"Katsu":(sheet_obj.cell(row = (30), column = 13).value),"Kayo":(sheet_obj.cell(row = (30), column = 14).value),"Levia":(sheet_obj.cell(row = (30), column = 15).value),"Maxx":(sheet_obj.cell(row = (30), column = 16).value),"Olympia":(sheet_obj.cell(row = (30), column = 17).value),"Prism":(sheet_obj.cell(row = (30), column = 18).value),"Rhinar":(sheet_obj.cell(row = (30), column = 19).value),"Riptide":(sheet_obj.cell(row = (30), column = 20).value),"Boltyn":(sheet_obj.cell(row = (30), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (30), column = 22).value),"Uzuri":(sheet_obj.cell(row = (30), column = 23).value),"Victor":(sheet_obj.cell(row = (30), column = 24).value),"Viserai":(sheet_obj.cell(row = (30), column = 25).value),"Vynnset":(sheet_obj.cell(row = (30), column = 26).value),"Enigma":(sheet_obj.cell(row = (30), column = 27).value),"Nuu":(sheet_obj.cell(row = (30), column = 28).value),"Zen":(sheet_obj.cell(row = (30), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (31), column = 3).value),"Azalea":(sheet_obj.cell(row = (31), column = 4).value),"Betsy":(sheet_obj.cell(row = (31), column = 5).value),"Bravo":(sheet_obj.cell(row = (31), column = 6).value),"DIO":(sheet_obj.cell(row = (31), column = 7).value),"Dash":(sheet_obj.cell(row = (31), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (31), column = 9).value),"Fai":(sheet_obj.cell(row = (31), column = 10).value),"Kano":(sheet_obj.cell(row = (31), column = 11).value),"Kassai":(sheet_obj.cell(row = (31), column = 12).value),"Katsu":(sheet_obj.cell(row = (31), column = 13).value),"Kayo":(sheet_obj.cell(row = (31), column = 14).value),"Levia":(sheet_obj.cell(row = (31), column = 15).value),"Maxx":(sheet_obj.cell(row = (31), column = 16).value),"Olympia":(sheet_obj.cell(row = (31), column = 17).value),"Prism":(sheet_obj.cell(row = (31), column = 18).value),"Rhinar":(sheet_obj.cell(row = (31), column = 19).value),"Riptide":(sheet_obj.cell(row = (31), column = 20).value),"Boltyn":(sheet_obj.cell(row = (31), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (31), column = 22).value),"Uzuri":(sheet_obj.cell(row = (31), column = 23).value),"Victor":(sheet_obj.cell(row = (31), column = 24).value),"Viserai":(sheet_obj.cell(row = (31), column = 25).value),"Vynnset":(sheet_obj.cell(row = (31), column = 26).value),"Enigma":(sheet_obj.cell(row = (31), column = 27).value),"Nuu":(sheet_obj.cell(row = (31), column = 28).value),"Zen":(sheet_obj.cell(row = (31), column = 29).value)}},
    'Prism':{'First':{"Arakni":(sheet_obj.cell(row = (32), column = 3).value),"Azalea":(sheet_obj.cell(row = (32), column = 4).value),"Betsy":(sheet_obj.cell(row = (32), column = 5).value),"Bravo":(sheet_obj.cell(row = (32), column = 6).value),"DIO":(sheet_obj.cell(row = (32), column = 7).value),"Dash":(sheet_obj.cell(row = (32), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (32), column = 9).value),"Fai":(sheet_obj.cell(row = (32), column = 10).value),"Kano":(sheet_obj.cell(row = (32), column = 11).value),"Kassai":(sheet_obj.cell(row = (32), column = 12).value),"Katsu":(sheet_obj.cell(row = (32), column = 13).value),"Kayo":(sheet_obj.cell(row = (32), column = 14).value),"Levia":(sheet_obj.cell(row = (32), column = 15).value),"Maxx":(sheet_obj.cell(row = (32), column = 16).value),"Olympia":(sheet_obj.cell(row = (32), column = 17).value),"Prism":(sheet_obj.cell(row = (32), column = 18).value),"Rhinar":(sheet_obj.cell(row = (32), column = 19).value),"Riptide":(sheet_obj.cell(row = (32), column = 20).value),"Boltyn":(sheet_obj.cell(row = (32), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (32), column = 22).value),"Uzuri":(sheet_obj.cell(row = (32), column = 23).value),"Victor":(sheet_obj.cell(row = (32), column = 24).value),"Viserai":(sheet_obj.cell(row = (32), column = 25).value),"Vynnset":(sheet_obj.cell(row = (32), column = 26).value),"Enigma":(sheet_obj.cell(row = (32), column = 27).value),"Nuu":(sheet_obj.cell(row = (32), column = 28).value),"Zen":(sheet_obj.cell(row = (32), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (33), column = 3).value),"Azalea":(sheet_obj.cell(row = (33), column = 4).value),"Betsy":(sheet_obj.cell(row = (33), column = 5).value),"Bravo":(sheet_obj.cell(row = (33), column = 6).value),"DIO":(sheet_obj.cell(row = (33), column = 7).value),"Dash":(sheet_obj.cell(row = (33), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (33), column = 9).value),"Fai":(sheet_obj.cell(row = (33), column = 10).value),"Kano":(sheet_obj.cell(row = (33), column = 11).value),"Kassai":(sheet_obj.cell(row = (33), column = 12).value),"Katsu":(sheet_obj.cell(row = (33), column = 13).value),"Kayo":(sheet_obj.cell(row = (33), column = 14).value),"Levia":(sheet_obj.cell(row = (33), column = 15).value),"Maxx":(sheet_obj.cell(row = (33), column = 16).value),"Olympia":(sheet_obj.cell(row = (33), column = 17).value),"Prism":(sheet_obj.cell(row = (33), column = 18).value),"Rhinar":(sheet_obj.cell(row = (33), column = 19).value),"Riptide":(sheet_obj.cell(row = (33), column = 20).value),"Boltyn":(sheet_obj.cell(row = (33), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (33), column = 22).value),"Uzuri":(sheet_obj.cell(row = (33), column = 23).value),"Victor":(sheet_obj.cell(row = (33), column = 24).value),"Viserai":(sheet_obj.cell(row = (33), column = 25).value),"Vynnset":(sheet_obj.cell(row = (33), column = 26).value),"Enigma":(sheet_obj.cell(row = (33), column = 27).value),"Nuu":(sheet_obj.cell(row = (33), column = 28).value),"Zen":(sheet_obj.cell(row = (33), column = 29).value)}},
    'Rhinar':{'First':{"Arakni":(sheet_obj.cell(row = (34), column = 3).value),"Azalea":(sheet_obj.cell(row = (34), column = 4).value),"Betsy":(sheet_obj.cell(row = (34), column = 5).value),"Bravo":(sheet_obj.cell(row = (34), column = 6).value),"DIO":(sheet_obj.cell(row = (34), column = 7).value),"Dash":(sheet_obj.cell(row = (34), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (34), column = 9).value),"Fai":(sheet_obj.cell(row = (34), column = 10).value),"Kano":(sheet_obj.cell(row = (34), column = 11).value),"Kassai":(sheet_obj.cell(row = (34), column = 12).value),"Katsu":(sheet_obj.cell(row = (34), column = 13).value),"Kayo":(sheet_obj.cell(row = (34), column = 14).value),"Levia":(sheet_obj.cell(row = (34), column = 15).value),"Maxx":(sheet_obj.cell(row = (34), column = 16).value),"Olympia":(sheet_obj.cell(row = (34), column = 17).value),"Prism":(sheet_obj.cell(row = (34), column = 18).value),"Rhinar":(sheet_obj.cell(row = (34), column = 19).value),"Riptide":(sheet_obj.cell(row = (34), column = 20).value),"Boltyn":(sheet_obj.cell(row = (34), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (34), column = 22).value),"Uzuri":(sheet_obj.cell(row = (34), column = 23).value),"Victor":(sheet_obj.cell(row = (34), column = 24).value),"Viserai":(sheet_obj.cell(row = (34), column = 25).value),"Vynnset":(sheet_obj.cell(row = (34), column = 26).value),"Enigma":(sheet_obj.cell(row = (34), column = 27).value),"Nuu":(sheet_obj.cell(row = (34), column = 28).value),"Zen":(sheet_obj.cell(row = (34), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (35), column = 3).value),"Azalea":(sheet_obj.cell(row = (35), column = 4).value),"Betsy":(sheet_obj.cell(row = (35), column = 5).value),"Bravo":(sheet_obj.cell(row = (35), column = 6).value),"DIO":(sheet_obj.cell(row = (35), column = 7).value),"Dash":(sheet_obj.cell(row = (35), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (35), column = 9).value),"Fai":(sheet_obj.cell(row = (35), column = 10).value),"Kano":(sheet_obj.cell(row = (35), column = 11).value),"Kassai":(sheet_obj.cell(row = (35), column = 12).value),"Katsu":(sheet_obj.cell(row = (35), column = 13).value),"Kayo":(sheet_obj.cell(row = (35), column = 14).value),"Levia":(sheet_obj.cell(row = (35), column = 15).value),"Maxx":(sheet_obj.cell(row = (35), column = 16).value),"Olympia":(sheet_obj.cell(row = (35), column = 17).value),"Prism":(sheet_obj.cell(row = (35), column = 18).value),"Rhinar":(sheet_obj.cell(row = (35), column = 19).value),"Riptide":(sheet_obj.cell(row = (35), column = 20).value),"Boltyn":(sheet_obj.cell(row = (35), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (35), column = 22).value),"Uzuri":(sheet_obj.cell(row = (35), column = 23).value),"Victor":(sheet_obj.cell(row = (35), column = 24).value),"Viserai":(sheet_obj.cell(row = (35), column = 25).value),"Vynnset":(sheet_obj.cell(row = (35), column = 26).value),"Enigma":(sheet_obj.cell(row = (35), column = 27).value),"Nuu":(sheet_obj.cell(row = (35), column = 28).value),"Zen":(sheet_obj.cell(row = (35), column = 29).value)}},
    'Riptide':{'First':{"Arakni":(sheet_obj.cell(row = (36), column = 3).value),"Azalea":(sheet_obj.cell(row = (36), column = 4).value),"Betsy":(sheet_obj.cell(row = (36), column = 5).value),"Bravo":(sheet_obj.cell(row = (36), column = 6).value),"DIO":(sheet_obj.cell(row = (36), column = 7).value),"Dash":(sheet_obj.cell(row = (36), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (36), column = 9).value),"Fai":(sheet_obj.cell(row = (36), column = 10).value),"Kano":(sheet_obj.cell(row = (36), column = 11).value),"Kassai":(sheet_obj.cell(row = (36), column = 12).value),"Katsu":(sheet_obj.cell(row = (36), column = 13).value),"Kayo":(sheet_obj.cell(row = (36), column = 14).value),"Levia":(sheet_obj.cell(row = (36), column = 15).value),"Maxx":(sheet_obj.cell(row = (36), column = 16).value),"Olympia":(sheet_obj.cell(row = (36), column = 17).value),"Prism":(sheet_obj.cell(row = (36), column = 18).value),"Rhinar":(sheet_obj.cell(row = (36), column = 19).value),"Riptide":(sheet_obj.cell(row = (36), column = 20).value),"Boltyn":(sheet_obj.cell(row = (36), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (36), column = 22).value),"Uzuri":(sheet_obj.cell(row = (36), column = 23).value),"Victor":(sheet_obj.cell(row = (36), column = 24).value),"Viserai":(sheet_obj.cell(row = (36), column = 25).value),"Vynnset":(sheet_obj.cell(row = (36), column = 26).value),"Enigma":(sheet_obj.cell(row = (36), column = 27).value),"Nuu":(sheet_obj.cell(row = (36), column = 28).value),"Zen":(sheet_obj.cell(row = (36), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (37), column = 3).value),"Azalea":(sheet_obj.cell(row = (37), column = 4).value),"Betsy":(sheet_obj.cell(row = (37), column = 5).value),"Bravo":(sheet_obj.cell(row = (37), column = 6).value),"DIO":(sheet_obj.cell(row = (37), column = 7).value),"Dash":(sheet_obj.cell(row = (37), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (37), column = 9).value),"Fai":(sheet_obj.cell(row = (37), column = 10).value),"Kano":(sheet_obj.cell(row = (37), column = 11).value),"Kassai":(sheet_obj.cell(row = (37), column = 12).value),"Katsu":(sheet_obj.cell(row = (37), column = 13).value),"Kayo":(sheet_obj.cell(row = (37), column = 14).value),"Levia":(sheet_obj.cell(row = (37), column = 15).value),"Maxx":(sheet_obj.cell(row = (37), column = 16).value),"Olympia":(sheet_obj.cell(row = (37), column = 17).value),"Prism":(sheet_obj.cell(row = (37), column = 18).value),"Rhinar":(sheet_obj.cell(row = (37), column = 19).value),"Riptide":(sheet_obj.cell(row = (37), column = 20).value),"Boltyn":(sheet_obj.cell(row = (37), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (37), column = 22).value),"Uzuri":(sheet_obj.cell(row = (37), column = 23).value),"Victor":(sheet_obj.cell(row = (37), column = 24).value),"Viserai":(sheet_obj.cell(row = (37), column = 25).value),"Vynnset":(sheet_obj.cell(row = (37), column = 26).value),"Enigma":(sheet_obj.cell(row = (37), column = 27).value),"Nuu":(sheet_obj.cell(row = (37), column = 28).value),"Zen":(sheet_obj.cell(row = (37), column = 29).value)}},
    'Boltyn':{'First':{"Arakni":(sheet_obj.cell(row = (38), column = 3).value),"Azalea":(sheet_obj.cell(row = (38), column = 4).value),"Betsy":(sheet_obj.cell(row = (38), column = 5).value),"Bravo":(sheet_obj.cell(row = (38), column = 6).value),"DIO":(sheet_obj.cell(row = (38), column = 7).value),"Dash":(sheet_obj.cell(row = (38), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (38), column = 9).value),"Fai":(sheet_obj.cell(row = (38), column = 10).value),"Kano":(sheet_obj.cell(row = (38), column = 11).value),"Kassai":(sheet_obj.cell(row = (38), column = 12).value),"Katsu":(sheet_obj.cell(row = (38), column = 13).value),"Kayo":(sheet_obj.cell(row = (38), column = 14).value),"Levia":(sheet_obj.cell(row = (38), column = 15).value),"Maxx":(sheet_obj.cell(row = (38), column = 16).value),"Olympia":(sheet_obj.cell(row = (38), column = 17).value),"Prism":(sheet_obj.cell(row = (38), column = 18).value),"Rhinar":(sheet_obj.cell(row = (38), column = 19).value),"Riptide":(sheet_obj.cell(row = (38), column = 20).value),"Boltyn":(sheet_obj.cell(row = (38), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (38), column = 22).value),"Uzuri":(sheet_obj.cell(row = (38), column = 23).value),"Victor":(sheet_obj.cell(row = (38), column = 24).value),"Viserai":(sheet_obj.cell(row = (38), column = 25).value),"Vynnset":(sheet_obj.cell(row = (38), column = 26).value),"Enigma":(sheet_obj.cell(row = (38), column = 27).value),"Nuu":(sheet_obj.cell(row = (38), column = 28).value),"Zen":(sheet_obj.cell(row = (38), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (39), column = 3).value),"Azalea":(sheet_obj.cell(row = (39), column = 4).value),"Betsy":(sheet_obj.cell(row = (39), column = 5).value),"Bravo":(sheet_obj.cell(row = (39), column = 6).value),"DIO":(sheet_obj.cell(row = (39), column = 7).value),"Dash":(sheet_obj.cell(row = (39), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (39), column = 9).value),"Fai":(sheet_obj.cell(row = (39), column = 10).value),"Kano":(sheet_obj.cell(row = (39), column = 11).value),"Kassai":(sheet_obj.cell(row = (39), column = 12).value),"Katsu":(sheet_obj.cell(row = (39), column = 13).value),"Kayo":(sheet_obj.cell(row = (39), column = 14).value),"Levia":(sheet_obj.cell(row = (39), column = 15).value),"Maxx":(sheet_obj.cell(row = (39), column = 16).value),"Olympia":(sheet_obj.cell(row = (39), column = 17).value),"Prism":(sheet_obj.cell(row = (39), column = 18).value),"Rhinar":(sheet_obj.cell(row = (39), column = 19).value),"Riptide":(sheet_obj.cell(row = (39), column = 20).value),"Boltyn":(sheet_obj.cell(row = (39), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (39), column = 22).value),"Uzuri":(sheet_obj.cell(row = (39), column = 23).value),"Victor":(sheet_obj.cell(row = (39), column = 24).value),"Viserai":(sheet_obj.cell(row = (39), column = 25).value),"Vynnset":(sheet_obj.cell(row = (39), column = 26).value),"Enigma":(sheet_obj.cell(row = (39), column = 27).value),"Nuu":(sheet_obj.cell(row = (39), column = 28).value),"Zen":(sheet_obj.cell(row = (39), column = 29).value)}},
    'Teklovossen':{'First':{"Arakni":(sheet_obj.cell(row = (40), column = 3).value),"Azalea":(sheet_obj.cell(row = (40), column = 4).value),"Betsy":(sheet_obj.cell(row = (40), column = 5).value),"Bravo":(sheet_obj.cell(row = (40), column = 6).value),"DIO":(sheet_obj.cell(row = (40), column = 7).value),"Dash":(sheet_obj.cell(row = (40), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (40), column = 9).value),"Fai":(sheet_obj.cell(row = (40), column = 10).value),"Kano":(sheet_obj.cell(row = (40), column = 11).value),"Kassai":(sheet_obj.cell(row = (40), column = 12).value),"Katsu":(sheet_obj.cell(row = (40), column = 13).value),"Kayo":(sheet_obj.cell(row = (40), column = 14).value),"Levia":(sheet_obj.cell(row = (40), column = 15).value),"Maxx":(sheet_obj.cell(row = (40), column = 16).value),"Olympia":(sheet_obj.cell(row = (40), column = 17).value),"Prism":(sheet_obj.cell(row = (40), column = 18).value),"Rhinar":(sheet_obj.cell(row = (40), column = 19).value),"Riptide":(sheet_obj.cell(row = (40), column = 20).value),"Boltyn":(sheet_obj.cell(row = (40), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (40), column = 22).value),"Uzuri":(sheet_obj.cell(row = (40), column = 23).value),"Victor":(sheet_obj.cell(row = (40), column = 24).value),"Viserai":(sheet_obj.cell(row = (40), column = 25).value),"Vynnset":(sheet_obj.cell(row = (40), column = 26).value),"Enigma":(sheet_obj.cell(row = (40), column = 27).value),"Nuu":(sheet_obj.cell(row = (40), column = 28).value),"Zen":(sheet_obj.cell(row = (40), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (41), column = 3).value),"Azalea":(sheet_obj.cell(row = (41), column = 4).value),"Betsy":(sheet_obj.cell(row = (41), column = 5).value),"Bravo":(sheet_obj.cell(row = (41), column = 6).value),"DIO":(sheet_obj.cell(row = (41), column = 7).value),"Dash":(sheet_obj.cell(row = (41), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (41), column = 9).value),"Fai":(sheet_obj.cell(row = (41), column = 10).value),"Kano":(sheet_obj.cell(row = (41), column = 11).value),"Kassai":(sheet_obj.cell(row = (41), column = 12).value),"Katsu":(sheet_obj.cell(row = (41), column = 13).value),"Kayo":(sheet_obj.cell(row = (41), column = 14).value),"Levia":(sheet_obj.cell(row = (41), column = 15).value),"Maxx":(sheet_obj.cell(row = (41), column = 16).value),"Olympia":(sheet_obj.cell(row = (41), column = 17).value),"Prism":(sheet_obj.cell(row = (41), column = 18).value),"Rhinar":(sheet_obj.cell(row = (41), column = 19).value),"Riptide":(sheet_obj.cell(row = (41), column = 20).value),"Boltyn":(sheet_obj.cell(row = (41), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (41), column = 22).value),"Uzuri":(sheet_obj.cell(row = (41), column = 23).value),"Victor":(sheet_obj.cell(row = (41), column = 24).value),"Viserai":(sheet_obj.cell(row = (41), column = 25).value),"Vynnset":(sheet_obj.cell(row = (41), column = 26).value),"Enigma":(sheet_obj.cell(row = (41), column = 27).value),"Nuu":(sheet_obj.cell(row = (41), column = 28).value),"Zen":(sheet_obj.cell(row = (41), column = 29).value)}},
    'Uzuri':{'First':{"Arakni":(sheet_obj.cell(row = (42), column = 3).value),"Azalea":(sheet_obj.cell(row = (42), column = 4).value),"Betsy":(sheet_obj.cell(row = (42), column = 5).value),"Bravo":(sheet_obj.cell(row = (42), column = 6).value),"DIO":(sheet_obj.cell(row = (42), column = 7).value),"Dash":(sheet_obj.cell(row = (42), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (42), column = 9).value),"Fai":(sheet_obj.cell(row = (42), column = 10).value),"Kano":(sheet_obj.cell(row = (42), column = 11).value),"Kassai":(sheet_obj.cell(row = (42), column = 12).value),"Katsu":(sheet_obj.cell(row = (42), column = 13).value),"Kayo":(sheet_obj.cell(row = (42), column = 14).value),"Levia":(sheet_obj.cell(row = (42), column = 15).value),"Maxx":(sheet_obj.cell(row = (42), column = 16).value),"Olympia":(sheet_obj.cell(row = (42), column = 17).value),"Prism":(sheet_obj.cell(row = (42), column = 18).value),"Rhinar":(sheet_obj.cell(row = (42), column = 19).value),"Riptide":(sheet_obj.cell(row = (42), column = 20).value),"Boltyn":(sheet_obj.cell(row = (42), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (42), column = 22).value),"Uzuri":(sheet_obj.cell(row = (42), column = 23).value),"Victor":(sheet_obj.cell(row = (42), column = 24).value),"Viserai":(sheet_obj.cell(row = (42), column = 25).value),"Vynnset":(sheet_obj.cell(row = (42), column = 26).value),"Enigma":(sheet_obj.cell(row = (42), column = 27).value),"Nuu":(sheet_obj.cell(row = (42), column = 28).value),"Zen":(sheet_obj.cell(row = (42), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (43), column = 3).value),"Azalea":(sheet_obj.cell(row = (43), column = 4).value),"Betsy":(sheet_obj.cell(row = (43), column = 5).value),"Bravo":(sheet_obj.cell(row = (43), column = 6).value),"DIO":(sheet_obj.cell(row = (43), column = 7).value),"Dash":(sheet_obj.cell(row = (43), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (43), column = 9).value),"Fai":(sheet_obj.cell(row = (43), column = 10).value),"Kano":(sheet_obj.cell(row = (43), column = 11).value),"Kassai":(sheet_obj.cell(row = (43), column = 12).value),"Katsu":(sheet_obj.cell(row = (43), column = 13).value),"Kayo":(sheet_obj.cell(row = (43), column = 14).value),"Levia":(sheet_obj.cell(row = (43), column = 15).value),"Maxx":(sheet_obj.cell(row = (43), column = 16).value),"Olympia":(sheet_obj.cell(row = (43), column = 17).value),"Prism":(sheet_obj.cell(row = (43), column = 18).value),"Rhinar":(sheet_obj.cell(row = (43), column = 19).value),"Riptide":(sheet_obj.cell(row = (43), column = 20).value),"Boltyn":(sheet_obj.cell(row = (43), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (43), column = 22).value),"Uzuri":(sheet_obj.cell(row = (43), column = 23).value),"Victor":(sheet_obj.cell(row = (43), column = 24).value),"Viserai":(sheet_obj.cell(row = (43), column = 25).value),"Vynnset":(sheet_obj.cell(row = (43), column = 26).value),"Enigma":(sheet_obj.cell(row = (43), column = 27).value),"Nuu":(sheet_obj.cell(row = (43), column = 28).value),"Zen":(sheet_obj.cell(row = (43), column = 29).value)}},
    'Victor':{'First':{"Arakni":(sheet_obj.cell(row = (44), column = 3).value),"Azalea":(sheet_obj.cell(row = (44), column = 4).value),"Betsy":(sheet_obj.cell(row = (44), column = 5).value),"Bravo":(sheet_obj.cell(row = (44), column = 6).value),"DIO":(sheet_obj.cell(row = (44), column = 7).value),"Dash":(sheet_obj.cell(row = (44), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (44), column = 9).value),"Fai":(sheet_obj.cell(row = (44), column = 10).value),"Kano":(sheet_obj.cell(row = (44), column = 11).value),"Kassai":(sheet_obj.cell(row = (44), column = 12).value),"Katsu":(sheet_obj.cell(row = (44), column = 13).value),"Kayo":(sheet_obj.cell(row = (44), column = 14).value),"Levia":(sheet_obj.cell(row = (44), column = 15).value),"Maxx":(sheet_obj.cell(row = (44), column = 16).value),"Olympia":(sheet_obj.cell(row = (44), column = 17).value),"Prism":(sheet_obj.cell(row = (44), column = 18).value),"Rhinar":(sheet_obj.cell(row = (44), column = 19).value),"Riptide":(sheet_obj.cell(row = (44), column = 20).value),"Boltyn":(sheet_obj.cell(row = (44), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (44), column = 22).value),"Uzuri":(sheet_obj.cell(row = (44), column = 23).value),"Victor":(sheet_obj.cell(row = (44), column = 24).value),"Viserai":(sheet_obj.cell(row = (44), column = 25).value),"Vynnset":(sheet_obj.cell(row = (44), column = 26).value),"Enigma":(sheet_obj.cell(row = (44), column = 27).value),"Nuu":(sheet_obj.cell(row = (44), column = 28).value),"Zen":(sheet_obj.cell(row = (44), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (45), column = 3).value),"Azalea":(sheet_obj.cell(row = (45), column = 4).value),"Betsy":(sheet_obj.cell(row = (45), column = 5).value),"Bravo":(sheet_obj.cell(row = (45), column = 6).value),"DIO":(sheet_obj.cell(row = (45), column = 7).value),"Dash":(sheet_obj.cell(row = (45), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (45), column = 9).value),"Fai":(sheet_obj.cell(row = (45), column = 10).value),"Kano":(sheet_obj.cell(row = (45), column = 11).value),"Kassai":(sheet_obj.cell(row = (45), column = 12).value),"Katsu":(sheet_obj.cell(row = (45), column = 13).value),"Kayo":(sheet_obj.cell(row = (45), column = 14).value),"Levia":(sheet_obj.cell(row = (45), column = 15).value),"Maxx":(sheet_obj.cell(row = (45), column = 16).value),"Olympia":(sheet_obj.cell(row = (45), column = 17).value),"Prism":(sheet_obj.cell(row = (45), column = 18).value),"Rhinar":(sheet_obj.cell(row = (45), column = 19).value),"Riptide":(sheet_obj.cell(row = (45), column = 20).value),"Boltyn":(sheet_obj.cell(row = (45), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (45), column = 22).value),"Uzuri":(sheet_obj.cell(row = (45), column = 23).value),"Victor":(sheet_obj.cell(row = (45), column = 24).value),"Viserai":(sheet_obj.cell(row = (45), column = 25).value),"Vynnset":(sheet_obj.cell(row = (45), column = 26).value),"Enigma":(sheet_obj.cell(row = (45), column = 27).value),"Nuu":(sheet_obj.cell(row = (45), column = 28).value),"Zen":(sheet_obj.cell(row = (45), column = 29).value)}},
    'Viserai':{'First':{"Arakni":(sheet_obj.cell(row = (46), column = 3).value),"Azalea":(sheet_obj.cell(row = (46), column = 4).value),"Betsy":(sheet_obj.cell(row = (46), column = 5).value),"Bravo":(sheet_obj.cell(row = (46), column = 6).value),"DIO":(sheet_obj.cell(row = (46), column = 7).value),"Dash":(sheet_obj.cell(row = (46), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (46), column = 9).value),"Fai":(sheet_obj.cell(row = (46), column = 10).value),"Kano":(sheet_obj.cell(row = (46), column = 11).value),"Kassai":(sheet_obj.cell(row = (46), column = 12).value),"Katsu":(sheet_obj.cell(row = (46), column = 13).value),"Kayo":(sheet_obj.cell(row = (46), column = 14).value),"Levia":(sheet_obj.cell(row = (46), column = 15).value),"Maxx":(sheet_obj.cell(row = (46), column = 16).value),"Olympia":(sheet_obj.cell(row = (46), column = 17).value),"Prism":(sheet_obj.cell(row = (46), column = 18).value),"Rhinar":(sheet_obj.cell(row = (46), column = 19).value),"Riptide":(sheet_obj.cell(row = (46), column = 20).value),"Boltyn":(sheet_obj.cell(row = (46), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (46), column = 22).value),"Uzuri":(sheet_obj.cell(row = (46), column = 23).value),"Victor":(sheet_obj.cell(row = (46), column = 24).value),"Viserai":(sheet_obj.cell(row = (46), column = 25).value),"Vynnset":(sheet_obj.cell(row = (46), column = 26).value),"Enigma":(sheet_obj.cell(row = (46), column = 27).value),"Nuu":(sheet_obj.cell(row = (46), column = 28).value),"Zen":(sheet_obj.cell(row = (46), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (47), column = 3).value),"Azalea":(sheet_obj.cell(row = (47), column = 4).value),"Betsy":(sheet_obj.cell(row = (47), column = 5).value),"Bravo":(sheet_obj.cell(row = (47), column = 6).value),"DIO":(sheet_obj.cell(row = (47), column = 7).value),"Dash":(sheet_obj.cell(row = (47), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (47), column = 9).value),"Fai":(sheet_obj.cell(row = (47), column = 10).value),"Kano":(sheet_obj.cell(row = (47), column = 11).value),"Kassai":(sheet_obj.cell(row = (47), column = 12).value),"Katsu":(sheet_obj.cell(row = (47), column = 13).value),"Kayo":(sheet_obj.cell(row = (47), column = 14).value),"Levia":(sheet_obj.cell(row = (47), column = 15).value),"Maxx":(sheet_obj.cell(row = (47), column = 16).value),"Olympia":(sheet_obj.cell(row = (47), column = 17).value),"Prism":(sheet_obj.cell(row = (47), column = 18).value),"Rhinar":(sheet_obj.cell(row = (47), column = 19).value),"Riptide":(sheet_obj.cell(row = (47), column = 20).value),"Boltyn":(sheet_obj.cell(row = (47), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (47), column = 22).value),"Uzuri":(sheet_obj.cell(row = (47), column = 23).value),"Victor":(sheet_obj.cell(row = (47), column = 24).value),"Viserai":(sheet_obj.cell(row = (47), column = 25).value),"Vynnset":(sheet_obj.cell(row = (47), column = 26).value),"Enigma":(sheet_obj.cell(row = (47), column = 27).value),"Nuu":(sheet_obj.cell(row = (47), column = 28).value),"Zen":(sheet_obj.cell(row = (47), column = 29).value)}},
    'Vynnset':{'First':{"Arakni":(sheet_obj.cell(row = (48), column = 3).value),"Azalea":(sheet_obj.cell(row = (48), column = 4).value),"Betsy":(sheet_obj.cell(row = (48), column = 5).value),"Bravo":(sheet_obj.cell(row = (48), column = 6).value),"DIO":(sheet_obj.cell(row = (48), column = 7).value),"Dash":(sheet_obj.cell(row = (48), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (48), column = 9).value),"Fai":(sheet_obj.cell(row = (48), column = 10).value),"Kano":(sheet_obj.cell(row = (48), column = 11).value),"Kassai":(sheet_obj.cell(row = (48), column = 12).value),"Katsu":(sheet_obj.cell(row = (48), column = 13).value),"Kayo":(sheet_obj.cell(row = (48), column = 14).value),"Levia":(sheet_obj.cell(row = (48), column = 15).value),"Maxx":(sheet_obj.cell(row = (48), column = 16).value),"Olympia":(sheet_obj.cell(row = (48), column = 17).value),"Prism":(sheet_obj.cell(row = (48), column = 18).value),"Rhinar":(sheet_obj.cell(row = (48), column = 19).value),"Riptide":(sheet_obj.cell(row = (48), column = 20).value),"Boltyn":(sheet_obj.cell(row = (48), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (48), column = 22).value),"Uzuri":(sheet_obj.cell(row = (48), column = 23).value),"Victor":(sheet_obj.cell(row = (48), column = 24).value),"Viserai":(sheet_obj.cell(row = (48), column = 25).value),"Vynnset":(sheet_obj.cell(row = (48), column = 26).value),"Enigma":(sheet_obj.cell(row = (48), column = 27).value),"Nuu":(sheet_obj.cell(row = (48), column = 28).value),"Zen":(sheet_obj.cell(row = (48), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (49), column = 3).value),"Azalea":(sheet_obj.cell(row = (49), column = 4).value),"Betsy":(sheet_obj.cell(row = (49), column = 5).value),"Bravo":(sheet_obj.cell(row = (49), column = 6).value),"DIO":(sheet_obj.cell(row = (49), column = 7).value),"Dash":(sheet_obj.cell(row = (49), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (49), column = 9).value),"Fai":(sheet_obj.cell(row = (49), column = 10).value),"Kano":(sheet_obj.cell(row = (49), column = 11).value),"Kassai":(sheet_obj.cell(row = (49), column = 12).value),"Katsu":(sheet_obj.cell(row = (49), column = 13).value),"Kayo":(sheet_obj.cell(row = (49), column = 14).value),"Levia":(sheet_obj.cell(row = (49), column = 15).value),"Maxx":(sheet_obj.cell(row = (49), column = 16).value),"Olympia":(sheet_obj.cell(row = (49), column = 17).value),"Prism":(sheet_obj.cell(row = (49), column = 18).value),"Rhinar":(sheet_obj.cell(row = (49), column = 19).value),"Riptide":(sheet_obj.cell(row = (49), column = 20).value),"Boltyn":(sheet_obj.cell(row = (49), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (49), column = 22).value),"Uzuri":(sheet_obj.cell(row = (49), column = 23).value),"Victor":(sheet_obj.cell(row = (49), column = 24).value),"Viserai":(sheet_obj.cell(row = (49), column = 25).value),"Vynnset":(sheet_obj.cell(row = (49), column = 26).value),"Enigma":(sheet_obj.cell(row = (49), column = 27).value),"Nuu":(sheet_obj.cell(row = (49), column = 28).value),"Zen":(sheet_obj.cell(row = (49), column = 29).value)}},
    'Enigma':{'First':{"Arakni":(sheet_obj.cell(row = (50), column = 3).value),"Azalea":(sheet_obj.cell(row = (50), column = 4).value),"Betsy":(sheet_obj.cell(row = (50), column = 5).value),"Bravo":(sheet_obj.cell(row = (50), column = 6).value),"DIO":(sheet_obj.cell(row = (50), column = 7).value),"Dash":(sheet_obj.cell(row = (50), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (50), column = 9).value),"Fai":(sheet_obj.cell(row = (50), column = 10).value),"Kano":(sheet_obj.cell(row = (50), column = 11).value),"Kassai":(sheet_obj.cell(row = (50), column = 12).value),"Katsu":(sheet_obj.cell(row = (50), column = 13).value),"Kayo":(sheet_obj.cell(row = (50), column = 14).value),"Levia":(sheet_obj.cell(row = (50), column = 15).value),"Maxx":(sheet_obj.cell(row = (50), column = 16).value),"Olympia":(sheet_obj.cell(row = (50), column = 17).value),"Prism":(sheet_obj.cell(row = (50), column = 18).value),"Rhinar":(sheet_obj.cell(row = (50), column = 19).value),"Riptide":(sheet_obj.cell(row = (50), column = 20).value),"Boltyn":(sheet_obj.cell(row = (50), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (50), column = 22).value),"Uzuri":(sheet_obj.cell(row = (50), column = 23).value),"Victor":(sheet_obj.cell(row = (50), column = 24).value),"Viserai":(sheet_obj.cell(row = (50), column = 25).value),"Vynnset":(sheet_obj.cell(row = (50), column = 26).value),"Enigma":(sheet_obj.cell(row = (50), column = 27).value),"Nuu":(sheet_obj.cell(row = (50), column = 28).value),"Zen":(sheet_obj.cell(row = (50), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (51), column = 3).value),"Azalea":(sheet_obj.cell(row = (51), column = 4).value),"Betsy":(sheet_obj.cell(row = (51), column = 5).value),"Bravo":(sheet_obj.cell(row = (51), column = 6).value),"DIO":(sheet_obj.cell(row = (51), column = 7).value),"Dash":(sheet_obj.cell(row = (51), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (51), column = 9).value),"Fai":(sheet_obj.cell(row = (51), column = 10).value),"Kano":(sheet_obj.cell(row = (51), column = 11).value),"Kassai":(sheet_obj.cell(row = (51), column = 12).value),"Katsu":(sheet_obj.cell(row = (51), column = 13).value),"Kayo":(sheet_obj.cell(row = (51), column = 14).value),"Levia":(sheet_obj.cell(row = (51), column = 15).value),"Maxx":(sheet_obj.cell(row = (51), column = 16).value),"Olympia":(sheet_obj.cell(row = (51), column = 17).value),"Prism":(sheet_obj.cell(row = (51), column = 18).value),"Rhinar":(sheet_obj.cell(row = (51), column = 19).value),"Riptide":(sheet_obj.cell(row = (51), column = 20).value),"Boltyn":(sheet_obj.cell(row = (51), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (51), column = 22).value),"Uzuri":(sheet_obj.cell(row = (51), column = 23).value),"Victor":(sheet_obj.cell(row = (51), column = 24).value),"Viserai":(sheet_obj.cell(row = (51), column = 25).value),"Vynnset":(sheet_obj.cell(row = (51), column = 26).value),"Enigma":(sheet_obj.cell(row = (51), column = 27).value),"Nuu":(sheet_obj.cell(row = (51), column = 28).value),"Zen":(sheet_obj.cell(row = (51), column = 29).value)}},
    'Nuu':{'First':{"Arakni":(sheet_obj.cell(row = (52), column = 3).value),"Azalea":(sheet_obj.cell(row = (52), column = 4).value),"Betsy":(sheet_obj.cell(row = (52), column = 5).value),"Bravo":(sheet_obj.cell(row = (52), column = 6).value),"DIO":(sheet_obj.cell(row = (52), column = 7).value),"Dash":(sheet_obj.cell(row = (52), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (52), column = 9).value),"Fai":(sheet_obj.cell(row = (52), column = 10).value),"Kano":(sheet_obj.cell(row = (52), column = 11).value),"Kassai":(sheet_obj.cell(row = (52), column = 12).value),"Katsu":(sheet_obj.cell(row = (52), column = 13).value),"Kayo":(sheet_obj.cell(row = (52), column = 14).value),"Levia":(sheet_obj.cell(row = (52), column = 15).value),"Maxx":(sheet_obj.cell(row = (52), column = 16).value),"Olympia":(sheet_obj.cell(row = (52), column = 17).value),"Prism":(sheet_obj.cell(row = (52), column = 18).value),"Rhinar":(sheet_obj.cell(row = (52), column = 19).value),"Riptide":(sheet_obj.cell(row = (52), column = 20).value),"Boltyn":(sheet_obj.cell(row = (52), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (52), column = 22).value),"Uzuri":(sheet_obj.cell(row = (52), column = 23).value),"Victor":(sheet_obj.cell(row = (52), column = 24).value),"Viserai":(sheet_obj.cell(row = (52), column = 25).value),"Vynnset":(sheet_obj.cell(row = (52), column = 26).value),"Enigma":(sheet_obj.cell(row = (52), column = 27).value),"Nuu":(sheet_obj.cell(row = (52), column = 28).value),"Zen":(sheet_obj.cell(row = (52), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (53), column = 3).value),"Azalea":(sheet_obj.cell(row = (53), column = 4).value),"Betsy":(sheet_obj.cell(row = (53), column = 5).value),"Bravo":(sheet_obj.cell(row = (53), column = 6).value),"DIO":(sheet_obj.cell(row = (53), column = 7).value),"Dash":(sheet_obj.cell(row = (53), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (53), column = 9).value),"Fai":(sheet_obj.cell(row = (53), column = 10).value),"Kano":(sheet_obj.cell(row = (53), column = 11).value),"Kassai":(sheet_obj.cell(row = (53), column = 12).value),"Katsu":(sheet_obj.cell(row = (53), column = 13).value),"Kayo":(sheet_obj.cell(row = (53), column = 14).value),"Levia":(sheet_obj.cell(row = (53), column = 15).value),"Maxx":(sheet_obj.cell(row = (53), column = 16).value),"Olympia":(sheet_obj.cell(row = (53), column = 17).value),"Prism":(sheet_obj.cell(row = (53), column = 18).value),"Rhinar":(sheet_obj.cell(row = (53), column = 19).value),"Riptide":(sheet_obj.cell(row = (53), column = 20).value),"Boltyn":(sheet_obj.cell(row = (53), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (53), column = 22).value),"Uzuri":(sheet_obj.cell(row = (53), column = 23).value),"Victor":(sheet_obj.cell(row = (53), column = 24).value),"Viserai":(sheet_obj.cell(row = (53), column = 25).value),"Vynnset":(sheet_obj.cell(row = (53), column = 26).value),"Enigma":(sheet_obj.cell(row = (53), column = 27).value),"Nuu":(sheet_obj.cell(row = (53), column = 28).value),"Zen":(sheet_obj.cell(row = (53), column = 29).value)}},
    'Zen':{'First':{"Arakni":(sheet_obj.cell(row = (54), column = 3).value),"Azalea":(sheet_obj.cell(row = (54), column = 4).value),"Betsy":(sheet_obj.cell(row = (54), column = 5).value),"Bravo":(sheet_obj.cell(row = (54), column = 6).value),"DIO":(sheet_obj.cell(row = (54), column = 7).value),"Dash":(sheet_obj.cell(row = (54), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (54), column = 9).value),"Fai":(sheet_obj.cell(row = (54), column = 10).value),"Kano":(sheet_obj.cell(row = (54), column = 11).value),"Kassai":(sheet_obj.cell(row = (54), column = 12).value),"Katsu":(sheet_obj.cell(row = (54), column = 13).value),"Kayo":(sheet_obj.cell(row = (54), column = 14).value),"Levia":(sheet_obj.cell(row = (54), column = 15).value),"Maxx":(sheet_obj.cell(row = (54), column = 16).value),"Olympia":(sheet_obj.cell(row = (54), column = 17).value),"Prism":(sheet_obj.cell(row = (54), column = 18).value),"Rhinar":(sheet_obj.cell(row = (54), column = 19).value),"Riptide":(sheet_obj.cell(row = (54), column = 20).value),"Boltyn":(sheet_obj.cell(row = (54), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (54), column = 22).value),"Uzuri":(sheet_obj.cell(row = (54), column = 23).value),"Victor":(sheet_obj.cell(row = (54), column = 24).value),"Viserai":(sheet_obj.cell(row = (54), column = 25).value),"Vynnset":(sheet_obj.cell(row = (54), column = 26).value),"Enigma":(sheet_obj.cell(row = (54), column = 27).value),"Nuu":(sheet_obj.cell(row = (54), column = 28).value),"Zen":(sheet_obj.cell(row = (54), column = 29).value)},
        'Second':{"Arakni":(sheet_obj.cell(row = (55), column = 3).value),"Azalea":(sheet_obj.cell(row = (55), column = 4).value),"Betsy":(sheet_obj.cell(row = (55), column = 5).value),"Bravo":(sheet_obj.cell(row = (55), column = 6).value),"DIO":(sheet_obj.cell(row = (55), column = 7).value),"Dash":(sheet_obj.cell(row = (55), column = 8).value),"Dorinthea":(sheet_obj.cell(row = (55), column = 9).value),"Fai":(sheet_obj.cell(row = (55), column = 10).value),"Kano":(sheet_obj.cell(row = (55), column = 11).value),"Kassai":(sheet_obj.cell(row = (55), column = 12).value),"Katsu":(sheet_obj.cell(row = (55), column = 13).value),"Kayo":(sheet_obj.cell(row = (55), column = 14).value),"Levia":(sheet_obj.cell(row = (55), column = 15).value),"Maxx":(sheet_obj.cell(row = (55), column = 16).value),"Olympia":(sheet_obj.cell(row = (55), column = 17).value),"Prism":(sheet_obj.cell(row = (55), column = 18).value),"Rhinar":(sheet_obj.cell(row = (55), column = 19).value),"Riptide":(sheet_obj.cell(row = (55), column = 20).value),"Boltyn":(sheet_obj.cell(row = (55), column = 21).value),"Teklovossen":(sheet_obj.cell(row = (55), column = 22).value),"Uzuri":(sheet_obj.cell(row = (55), column = 23).value),"Victor":(sheet_obj.cell(row = (55), column = 24).value),"Viserai":(sheet_obj.cell(row = (55), column = 25).value),"Vynnset":(sheet_obj.cell(row = (55), column = 26).value),"Enigma":(sheet_obj.cell(row = (55), column = 27).value),"Nuu":(sheet_obj.cell(row = (55), column = 28).value),"Zen":(sheet_obj.cell(row = (55), column = 29).value)}}}




#Swiss Pairings Logic
def generate_pairings(players, previous_pairings=None, results=None):
    pairings = []
    if previous_pairings is None:
        previous_pairings = set()  # Initialize an empty set for previous pairings
    if results is None:
        results = {}  # Initialize an empty dictionary for results
    
    # Group players based on their current results
    result_groups = {}
    for player in players:
        result = results.get(player, 0)
        if result not in result_groups:
            result_groups[result] = []
        result_groups[result].append(player)


    
    # Sort result groups based on results
    sorted_result_groups = sorted(result_groups.items(), key=lambda x: x[0], reverse=True)


    # Pair players with similar results
    for i, (result, group) in enumerate(sorted_result_groups):
        if len(group) % 2 != 0:
            # If there's an odd number of players in the group, try to pair with the highest-ranked player in the next lowest group
            next_group_index = i + 1
            while next_group_index < len(sorted_result_groups):
                next_result, next_group = sorted_result_groups[next_group_index]
                if len(next_group) > 0:
                    odd_player = group[0]
                    random.shuffle(next_group)
                    pair = (group[0], next_group[0])
                    while pair in previous_pairings or pair[::-1] in previous_pairings:
                        random.shuffle(next_group)
                        random.shuffle(group)# Shuffle players again to try different pairings
                        pair = (group[0], next_group[0])
                        if len(next_group) == 3:
                            pair2 = (next_group[1], next_group[2])
                            while pair2 in previous_pairings or pair[::-1] in previous_pairings:
                                random.shuffle(next_group)
                                pair = (group[0], next_group[0])
                            if len(group) == 3:
                                pair3 = ((group[1], group[2]))
                                while pair3 in previous_pairings or pair[::-1] in previous_pairings:
                                    random.shuffle(group)
                                    pair = (group[0], next_group[0])
                    odd_player = group.pop()
                    paired_player = next_group.pop(0)
                    pairings.append((odd_player, paired_player))
                    previous_pairings.add((odd_player, paired_player))
                    break
                next_group_index += 1
            else:
                # If no suitable pairing found, give the odd player a bye (free win)
                odd_player = group.pop()
                results[odd_player] = 1
        random.shuffle(group)  # Randomize player order within the group
        for j in range(0, len(group), 2):
            pair = (group[j], group[j+1])
            while pair in previous_pairings or pair[::-1] in previous_pairings:
                random.shuffle(group)  # Shuffle players again to try different pairings
                pair = (group[j], group[j+1])
            pairings.append(pair)
            previous_pairings.add(pair)
    
    return pairings, previous_pairings

def simulate_round(pairings):
    # Simulate games for each pairing
    results = {}
    for pair in pairings:
        # Simulate game between pair[0] and pair[1]
        # Update results based on game outcome (win, loss, draw)
        # For simplicity, let's assume random results
        Coin_Flip = random.randint(1,2)
        if Coin_Flip == 1:
            Hero1 = Player_List.get(pair[0])
            Hero2 = Player_List.get(pair[1])
            Weight = Matchups[Hero1]["First"][Hero2]
        elif Coin_Flip == 2:
            Hero1 = Player_List.get(pair[0])
            Hero2 = Player_List.get(pair[1])
            Weight = Matchups[Hero1]["Second"][Hero2]
        Deceider = round(random.uniform(0,1),2)
        results[pair[0]] = 'win' if Deceider <= Weight else 'loss' if Deceider > Weight else 'draw'
        results[pair[1]] = 'win' if results[pair[0]] == 'loss' else 'loss' if results[pair[0]] == 'win' else 'draw'
    return results


previous_pairings = set()
results = {key: 0 for key in Player_List.keys()}
Tie_Breakers = {key: 0 for key in Player_List.keys()}
for round_num in range(int(Rounds)):
    round_num+1
    """print("\n" "Round", round_num+1)"""
    pairings, previous_pairings = generate_pairings(players, previous_pairings, results)
    """print("\n" "Pairings:", pairings)"""
    round_results = simulate_round(pairings)
    """print("\n" "Results:", round_results)"""
    for player in round_results:
        if round_results.get(player) == 'win':
            results[player] += 1
            Tie_Breakers[player] += (int(Rounds)-(int(round_num)-1))
        elif round_results.get(player) == 'lose':
            results[player] += 0
            

#Add Tiebreaker values to records to find tie breakers
for player in results:
    results[player] += Tie_Breakers[player]

#dictionary for top 64 hero counts
Hero_Results = []

for player in results:
    Hero_Results.append(((Player_List[player]),(results[player])))

sorted_overall_results = sorted(Hero_Results, key=lambda x: x[1], reverse=True)

#Dictionary for just hero names for placing
clean_results = []
a = 0

#Strip anything but hero name from results
while a < len(sorted_overall_results):
    clean = str(sorted_overall_results[a])
    clean = re.sub("[(),1234567890' ]", '', clean)
    clean_results.append(clean)
    a += 1
print("\n")

#Set Excel defaults to output file
path = "Calculator Export.xlsx"
wb_obj = openpyxl.load_workbook(path)
wb_obj.create_sheet(Sheet_Name)
wb_obj.active = wb_obj[Sheet_Name]
sheet_obj = wb_obj.active

#Set columns for new sheet_obj
sheet_obj.cell(row=(1),column=(1)).value = "Placement"
sheet_obj.cell(row=(1),column=(2)).value = "Hero"
sheet_obj.cell(row=(1),column=(5)).value = "Top 64 Breakdown"
sheet_obj.cell(row=(1),column=(6)).value = "Hero"
sheet_obj.cell(row=(1),column=(7)).value = "Number"

#print data to workbook
place = 0
top_sixtyfour = dict()
try:
    while place < 64:
        top_sixtyfour[clean_results[place]] = top_sixtyfour.get(clean_results[place], 0)+1
        sheet_obj.cell(row = ((int(place)+2)), column = 1).value = (int(place)+1)
        sheet_obj.cell(row = ((int(place)+2)), column = 2).value = clean_results[place]
        """print(f"{(int(place)+1)} = ",clean_results[place])"""
        place += 1
except IndexError:
    pass

#Set Hero data for top 64
excel_spot = 2
for hero in top_sixtyfour.keys():
    sheet_obj.cell(row = (excel_spot), column = 6).value = hero
    excel_spot += 1
    
excel_spot = 2
for hero in top_sixtyfour.values():
    sheet_obj.cell(row = (excel_spot), column = 7).value = hero
    excel_spot += 1
    
wb_obj.save("Calculator Export.xlsx")
"""
print("\n",top_sixtyfour)
"""   
""" 
print("\n" "Overall Results =",sorted_overall_results)
"""
